import 'dart:io';

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../l10n/app_localizations.dart';
import '../models/environment_log.dart';
import '../models/grow_space.dart';
import '../models/plant.dart';
import '../models/plant_note.dart';
import '../repository/grow_repository.dart';
import '../theme/app_colors.dart';
import '../theme/app_spacing.dart';
import '../theme/app_typography.dart';
import '../utils/home_reminders.dart';
import '../utils/image_cache_size.dart';
import '../utils/photo_path_resolver.dart';
import '../utils/temp_format.dart';
import '../widgets/app_card.dart';
import '../widgets/app_sheet.dart';
import '../widgets/app_toast.dart';
import '../widgets/batch_care_sheet.dart';
import '../widgets/empty_state_art.dart';
import '../widgets/open_issues_banner.dart';
import '../widgets/skeleton.dart';
import '../widgets/status_badge.dart';
import 'nutrient_calculator_screen.dart';
import 'plant_detail_screen.dart';
import 'search_screen.dart';
import 'settings_screen.dart';
import 'space_detail_screen.dart' as space_screen;

class HomeScreen extends StatefulWidget {
  const HomeScreen({super.key});

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> {
  /// F9 — when non-null, the SliverList only renders space cards whose
  /// plant list contains at least one plant of this strain.  Plant
  /// counts in each card also collapse to "of strain X" so the visual
  /// matches the filter.  Cleared via the chip's close button.
  String? _strainFilter;

  @override
  Widget build(BuildContext context) {
    final repo = context.watch<GrowRepository>();

    // ── Pre-aggregate everything the home screen needs in ONE pass over
    //    each collection.  Previously each Space card re-ran an O(N)
    //    `where().toList()` per build × per space, which compounded fast
    //    on every repo notification (env log added, plant edited, etc.).
    //    Now: O(plants + spaces + envLogs), with O(1) lookups inside the
    //    SliverList builder.
    final activePlants = <Plant>[];
    final plantsBySpace = <String, List<Plant>>{};
    // F9 — collect the distinct strain pool *before* applying the filter
    // so the chooser sheet always shows every active strain (otherwise
    // selecting one strain would hide the rest from the picker).
    final activeStrainSet = <String>{};
    final filter = _strainFilter;
    for (final p in repo.plants) {
      if (p.isArchived) continue;
      if (p.strain.isNotEmpty) activeStrainSet.add(p.strain);
      if (filter != null && p.strain != filter) continue;
      activePlants.add(p);
      (plantsBySpace[p.growSpaceId] ??= <Plant>[]).add(p);
    }
    final activeStrains = activeStrainSet.toList()..sort();

    final spaceIdSet = <String>{for (final s in repo.growSpaces) s.id};
    final orphans = [
      for (final p in activePlants)
        if (!spaceIdSet.contains(p.growSpaceId)) p
    ];

    // Newest env log per space — single linear pass instead of N sorts.
    final latestLogBySpace = <String, EnvironmentLog>{};
    for (final l in repo.environmentLogs) {
      final cur = latestLogBySpace[l.growSpaceId];
      if (cur == null || l.recordedAt.isAfter(cur.recordedAt)) {
        latestLogBySpace[l.growSpaceId] = l;
      }
    }

    return Scaffold(
      body: CustomScrollView(
        slivers: [
          // ── App bar ──────────────────────────
          SliverAppBar(
            pinned: true,
            title: Row(
              children: [
                // Kultivar mark — bundled via `assets/branding/` in
                // pubspec, generated by the launcher-icon pipeline.
                // The PNG is white-on-transparent so it sits cleanly
                // against any AppBar background; tinted to the primary
                // brand green via `ColorFiltered` so the mark stays in
                // visual lockstep with the "Kultivar" wordmark next to
                // it instead of competing as a separate colour.
                // A9 — decorative-only.  The "Kultivar" wordmark
                // immediately to the right already announces the brand
                // name to screen readers; labelling the image would
                // make TalkBack/VoiceOver pronounce "Kultivar" twice
                // (once for the alt text, once for the Text widget).
                ColorFiltered(
                  colorFilter: const ColorFilter.mode(
                    AppColors.primary,
                    BlendMode.srcIn,
                  ),
                  child: Image.asset(
                    'assets/branding/icon_foreground.png',
                    width: 22,
                    height: 22,
                    fit: BoxFit.contain,
                    filterQuality: FilterQuality.medium,
                    excludeFromSemantics: true,
                  ),
                ),
                const SizedBox(width: AppSpacing.xs),
                // Bug fix v4: pin an explicit fontSize + clamp text
                // scaler so a user-elevated system text-scale (Samsung
                // "Large fonts") can't overflow the AppBar vertically.
                // 22 px matches headlineSmall in normal scale; pinning
                // the size keeps the wordmark on one line at any scale.
                MediaQuery.withClampedTextScaling(
                  maxScaleFactor: 1.0,
                  child: Text(
                    'Kultivar',
                    style: AppTypography.headlineMedium(context).copyWith(
                      color: AppColors.primary,
                      fontSize: 22,
                      height: 1.0,
                    ),
                    maxLines: 1,
                    overflow: TextOverflow.clip,
                  ),
                ),
              ],
            ),
            actions: [
              // ── Reminders bell ─────────────────
              Builder(builder: (ctx) {
                final reminders = buildHomeReminders(repo.plants, repo.notes,
                    spaces: repo.growSpaces,
                    envLogs: repo.environmentLogs);
                final urgent = reminders.where((r) => r.isUrgent).length;
                // UX10 — show the next-action label in the tooltip so a
                // long-press peek surfaces "Water Blue Dream · 2 more"
                // without opening the full sheet.  Single-tap behaviour
                // (open sheet) is unchanged so users who know what
                // they're doing don't pay the peek cost.
                final tooltip = reminders.isEmpty
                    ? 'Reminders'
                    : (reminders.length == 1
                        ? reminders.first.peekLabel
                        : '${reminders.first.peekLabel} · '
                            '${reminders.length - 1} more');
                return Stack(
                  alignment: Alignment.center,
                  children: [
                    IconButton(
                      icon: Icon(Icons.notifications_outlined,
                          color: urgent > 0
                              ? AppColors.warning
                              : context.colTextSecondary),
                      tooltip: tooltip,
                      onPressed: () => _showRemindersSheet(
                          ctx, repo.plants, repo.notes,
                          spaces: repo.growSpaces,
                          envLogs: repo.environmentLogs),
                    ),
                    if (urgent > 0)
                      Positioned(
                        top: 8,
                        right: 8,
                        child: Container(
                          width: 16,
                          height: 16,
                          decoration: const BoxDecoration(
                            color: AppColors.warning,
                            shape: BoxShape.circle,
                          ),
                          child: Center(
                            child: Text(
                              urgent > 9 ? '9+' : '$urgent',
                              style: const TextStyle(
                                  fontSize: 9,
                                  fontWeight: FontWeight.bold,
                                  color: Colors.black),
                            ),
                          ),
                        ),
                      ),
                  ],
                );
              }),
              // Bug fix v4: Marco flagged the Home AppBar as still
              // too crowded.  Calendar + Notes were the heaviest
              // secondary-nav items.  Moved both to the Analytics
              // AppBar where there's clearly room.  Home AppBar now
              // holds only: bell, strain-filter (conditional),
              // search, settings, chip (conditional).
              // F9 — strain-filter chip.  Hidden when only zero or one
              // strain is in active rotation (filter would be a no-op).
              if (activeStrains.length > 1)
                IconButton(
                  icon: Icon(
                    Icons.science_rounded,
                    color: _strainFilter != null
                        ? AppColors.primary
                        : context.colTextSecondary,
                  ),
                  tooltip: _strainFilter != null
                      ? 'Filter: $_strainFilter'
                      : 'Filter by strain',
                  onPressed: () => _showStrainFilterSheet(context,
                      activeStrains),
                ),
              IconButton(
                icon: Icon(Icons.search_rounded,
                    color: context.colTextSecondary),
                tooltip: 'Search',
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => const SearchScreen(),
                  ),
                ),
              ),
              // Bug fix v2: Settings moved off the bottom nav and into
              // the AppBar (gear icon).  Placed last so it's the
              // rightmost item -- standard Material convention.
              IconButton(
                icon: Icon(Icons.settings_rounded,
                    color: context.colTextSecondary),
                tooltip: 'Settings',
                onPressed: () => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => const SettingsScreen(),
                  ),
                ),
              ),
              // Active plant count badge.
              //
              // Bug fix v2: when the strain-filter icon is also
              // present (>1 active strain), the AppBar carries 5
              // actions + this chip + the wordmark -- which
              // overflows the S22 by 9 px.  Hide the chip in that
              // case; the same information lives in the Home grid
              // header anyway.
              if (activePlants.isNotEmpty && activeStrains.length <= 1)
                Container(
                  margin: const EdgeInsets.only(right: AppSpacing.sm),
                  padding:
                      const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: AppColors.primary.withValues(alpha: 0.12),
                    borderRadius: BorderRadius.circular(AppSpacing.radiusFull),
                    border: Border.all(
                        color: AppColors.primary.withValues(alpha: 0.3)),
                  ),
                  child: Text(
                    // F11 — ICU plural; resolves to "1 active",
                    // "3 active", "1 activa", "3 aktiv", etc.
                    AppLocalizations.of(context)
                        .homeActivePlants(activePlants.length),
                    style: AppTypography.labelSmall(context)
                        .copyWith(color: AppColors.primary),
                  ),
                ),
            ],
          ),

          if (repo.growSpaces.isEmpty)
            // A6 — distinguish "still loading from disk" from
            // "truly empty new install".  When the initial repo
            // load() hasn't finished, render shimmer skeleton cards
            // (perceived snappier than flashing the empty-state
            // hero then re-rendering to populated data 100 ms
            // later).  Once load() settles, fall through to either
            // the populated grid (data found) or the empty-state
            // hero (genuinely no spaces yet).
            if (repo.isLoading)
              SliverList(
                delegate: SliverChildBuilderDelegate(
                  (_, __) => const SkeletonSpaceCard(),
                  childCount: 3,
                ),
              )
            else
              const SliverFillRemaining(
                child: _HomeEmptyState(),
              )
          else ...[
            // F9 — active strain-filter banner.  Mirrors the chip in
            // the app bar but gives a one-tap "Clear" target that
            // doesn't require remembering which icon toggles it.
            if (_strainFilter != null)
              SliverToBoxAdapter(
                child: Container(
                  margin: const EdgeInsets.fromLTRB(
                      AppSpacing.pagePadding,
                      AppSpacing.xs,
                      AppSpacing.pagePadding,
                      AppSpacing.xs),
                  padding: const EdgeInsets.symmetric(
                      horizontal: AppSpacing.sm, vertical: 6),
                  decoration: BoxDecoration(
                    color: AppColors.primary.withValues(alpha: 0.08),
                    borderRadius:
                        BorderRadius.circular(AppSpacing.radiusFull),
                    border: Border.all(
                        color: AppColors.primary.withValues(alpha: 0.3)),
                  ),
                  child: Row(children: [
                    const Icon(Icons.science_rounded,
                        size: 14, color: AppColors.primary),
                    const SizedBox(width: AppSpacing.xs),
                    Expanded(
                      child: Text(
                        'Filtering by strain: $_strainFilter',
                        style: AppTypography.labelSmall(context)
                            .copyWith(color: AppColors.primary),
                      ),
                    ),
                    InkWell(
                      onTap: () => setState(() => _strainFilter = null),
                      borderRadius: BorderRadius.circular(12),
                      child: const Padding(
                        padding: EdgeInsets.all(2),
                        child: Icon(Icons.close_rounded,
                            size: 14, color: AppColors.primary),
                      ),
                    ),
                  ]),
                ),
              ),
            // ── Open issues banner ────────────────
            SliverToBoxAdapter(
              child: OpenIssuesBanner(
                plants: repo.plants,
                allNotes: repo.notes,
                repo: repo,
                onPlantTap: (plant) => Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (_) => PlantDetailScreen(plant: plant),
                  ),
                ),
              ),
            ),

            // ── Orphaned-plant safety net ─────────
            // Catches any non-archived plant whose growSpaceId no longer
            // matches an existing space (e.g. data imported from backup).
            // Uses the orphans list precomputed at the top of build —
            // saves an O(plants) scan + Set-allocation per rebuild.
            Builder(builder: (context) {
              if (orphans.isEmpty) return const SliverToBoxAdapter();
              return SliverToBoxAdapter(
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(
                    AppSpacing.pagePadding,
                    0,
                    AppSpacing.pagePadding,
                    AppSpacing.md,
                  ),
                  child: Container(
                    padding: const EdgeInsets.all(AppSpacing.md),
                    decoration: BoxDecoration(
                      color: AppColors.warning.withValues(alpha: 0.08),
                      borderRadius:
                          BorderRadius.circular(AppSpacing.radiusMd),
                      border: Border.all(
                          color: AppColors.warning.withValues(alpha: 0.35)),
                    ),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(children: [
                          const Icon(Icons.warning_amber_rounded,
                              color: AppColors.warning, size: 18),
                          const SizedBox(width: AppSpacing.xs),
                          Text(
                            'Unassigned Plants (${orphans.length})',
                            style: AppTypography.labelLarge(context)
                                .copyWith(color: AppColors.warning),
                          ),
                        ]),
                        const SizedBox(height: AppSpacing.xs),
                        Text(
                          "These plants' grow space no longer exists. "
                          'Tap a plant to reassign it.',
                          style: AppTypography.bodySmall(context)
                              .copyWith(color: context.colTextSecondary),
                        ),
                        const SizedBox(height: AppSpacing.sm),
                        ...orphans.map((plant) {
                          final color =
                              AppColors.statusColor(plant.statusLabel);
                          return GestureDetector(
                            onTap: () => Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (_) =>
                                    PlantDetailScreen(plant: plant),
                              ),
                            ),
                            child: Container(
                              margin: const EdgeInsets.only(
                                  bottom: AppSpacing.xs),
                              padding: const EdgeInsets.symmetric(
                                horizontal: AppSpacing.sm,
                                vertical: AppSpacing.xs,
                              ),
                              decoration: BoxDecoration(
                                color: context.colSurface2,
                                borderRadius: BorderRadius.circular(
                                    AppSpacing.radiusSm),
                                border: Border.all(
                                    color: color.withValues(alpha: 0.3)),
                              ),
                              child: Row(children: [
                                Container(
                                  width: 6,
                                  height: 6,
                                  margin: const EdgeInsets.only(
                                      right: AppSpacing.xs),
                                  decoration: BoxDecoration(
                                      shape: BoxShape.circle, color: color),
                                ),
                                Expanded(
                                  child: Text(
                                    '${plant.name} · ${plant.statusLabel}',
                                    style:
                                        AppTypography.bodyMedium(context),
                                  ),
                                ),
                                Icon(Icons.chevron_right,
                                    size: 14,
                                    color: context.colTextMuted),
                              ]),
                            ),
                          );
                        }),
                      ],
                    ),
                  ),
                ),
              );
            }),

            SliverPadding(
              padding: const EdgeInsets.all(AppSpacing.pagePadding),
              sliver: SliverList(
                delegate: SliverChildBuilderDelegate(
                  (_, i) {
                    final space = repo.growSpaces[i];
                    // O(1) lookups instead of per-space O(N) scans —
                    // see the pre-aggregation block at the top of build.
                    final plants = plantsBySpace[space.id] ?? const <Plant>[];
                    final latest = latestLogBySpace[space.id];

                    return Padding(
                      padding: const EdgeInsets.only(bottom: AppSpacing.md),
                      child: _SpaceCard(
                        // PageStorageKey preserves _expanded state across
                        // list rebuilds triggered by repo changes.
                        key: PageStorageKey(space.id),
                        space: space,
                        plants: plants,
                        latestTemp: latest?.temperature,
                        latestHumidity: latest?.humidity,
                        // isOptimalAvailable returns null when readings are
                        // absent, true/false otherwise — cleanly separates
                        // "no data" from "out of range".
                        isOptimal: space.isOptimalAvailable(
                            latest?.temperature, latest?.humidity),
                        latestRecordedAt: latest?.recordedAt,
                      ),
                    );
                  },
                  childCount: repo.growSpaces.length,
                ),
              ),
            ),
          ],  // closes else ...[
        ],    // closes slivers: [
      ),
    );
  }

  // ── F9 — strain filter chooser ────────────────

  void _showStrainFilterSheet(BuildContext context, List<String> strains) {
    showModalBottomSheet<void>(
      context: context,
      backgroundColor: context.colSurface2,
      shape: const RoundedRectangleBorder(
        borderRadius:
            BorderRadius.vertical(top: Radius.circular(AppSpacing.radiusXl)),
      ),
      builder: (ctx) => SafeArea(
        child: ConstrainedBox(
          constraints: BoxConstraints(
            maxHeight: MediaQuery.of(ctx).size.height * 0.6,
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Padding(
                padding: const EdgeInsets.fromLTRB(
                    AppSpacing.pagePadding,
                    AppSpacing.md,
                    AppSpacing.pagePadding,
                    AppSpacing.xs),
                child: Row(children: [
                  const Icon(Icons.science_rounded,
                      color: AppColors.primary, size: 20),
                  const SizedBox(width: AppSpacing.sm),
                  Text('Filter by strain',
                      style: AppTypography.headlineMedium(ctx)),
                ]),
              ),
              Padding(
                padding: const EdgeInsets.symmetric(
                    horizontal: AppSpacing.pagePadding),
                child: Text(
                  'Only show grow spaces whose plants include this strain. '
                  'Useful for comparing same-strain runs side-by-side.',
                  style: AppTypography.bodySmall(ctx)
                      .copyWith(color: ctx.colTextMuted),
                ),
              ),
              const SizedBox(height: AppSpacing.sm),
              Divider(color: ctx.colBorderFaint, height: 1),
              Flexible(
                child: ListView(
                  shrinkWrap: true,
                  children: [
                    // "All strains" sentinel resets the filter.
                    ListTile(
                      leading: Icon(Icons.clear_all_rounded,
                          color: _strainFilter == null
                              ? AppColors.primary
                              : ctx.colTextMuted),
                      title: Text('All strains',
                          style: AppTypography.labelLarge(ctx)),
                      trailing: _strainFilter == null
                          ? const Icon(Icons.check_rounded,
                              color: AppColors.primary, size: 20)
                          : null,
                      onTap: () {
                        setState(() => _strainFilter = null);
                        Navigator.pop(ctx);
                      },
                    ),
                    for (final s in strains)
                      ListTile(
                        leading: const Icon(Icons.eco_rounded,
                            color: AppColors.growing),
                        title:
                            Text(s, style: AppTypography.labelLarge(ctx)),
                        trailing: _strainFilter == s
                            ? const Icon(Icons.check_rounded,
                                color: AppColors.primary, size: 20)
                            : null,
                        onTap: () {
                          setState(() => _strainFilter = s);
                          Navigator.pop(ctx);
                        },
                      ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  // ── Reminder logic ────────────────────────────
  //
  // Lives in [buildHomeReminders] (utils/home_reminders.dart) so the
  // logic is unit-testable and reusable from other surfaces.  The
  // home screen no longer owns the rules — it just renders them.

  void _showRemindersSheet(
    BuildContext context,
    List<Plant> plants,
    List<PlantNote> notes, {
    List<GrowSpace> spaces = const [],
    List<EnvironmentLog> envLogs = const [],
  }) {
    final reminders = buildHomeReminders(plants, notes,
        spaces: spaces, envLogs: envLogs);
    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      backgroundColor: context.colSurface1,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(
            top: Radius.circular(AppSpacing.radiusLg)),
      ),
      builder: (ctx) => DraggableScrollableSheet(
        expand: false,
        initialChildSize: reminders.isEmpty ? 0.35 : 0.55,
        maxChildSize: 0.85,
        minChildSize: 0.3,
        builder: (_, controller) => Column(
          children: [
            // Handle
            Container(
              margin: const EdgeInsets.only(top: 10, bottom: 6),
              width: 36,
              height: 4,
              decoration: BoxDecoration(
                color: ctx.colBorder,
                borderRadius: BorderRadius.circular(AppSpacing.radiusFull),
              ),
            ),
            // Header
            Padding(
              padding: const EdgeInsets.symmetric(
                  horizontal: AppSpacing.pagePadding, vertical: AppSpacing.sm),
              child: Row(
                children: [
                  const Icon(Icons.notifications_rounded,
                      color: AppColors.primary, size: 20),
                  const SizedBox(width: AppSpacing.xs),
                  Text('Reminders',
                      style: AppTypography.headlineMedium(ctx)),
                  const Spacer(),
                  if (reminders.isNotEmpty)
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 2),
                      decoration: BoxDecoration(
                        color: AppColors.warning.withValues(alpha: 0.15),
                        borderRadius:
                            BorderRadius.circular(AppSpacing.radiusFull),
                      ),
                      child: Text(
                        '${reminders.length}',
                        style: AppTypography.labelSmall(ctx)
                            .copyWith(color: AppColors.warning),
                      ),
                    ),
                ],
              ),
            ),
            const Divider(height: 1),
            // Content
            Expanded(
              child: reminders.isEmpty
                  ? Center(
                      child: Column(
                        mainAxisSize: MainAxisSize.min,
                        children: [
                          Icon(Icons.check_circle_outline_rounded,
                              size: 44, color: ctx.colTextMuted),
                          const SizedBox(height: AppSpacing.sm),
                          Text('All clear!',
                              style: AppTypography.headlineSmall(ctx)),
                          const SizedBox(height: AppSpacing.xs),
                          Text(
                            'No upcoming or overdue events\nwithin the next 7 days.',
                            textAlign: TextAlign.center,
                            style: AppTypography.bodySmall(ctx)
                                .copyWith(color: ctx.colTextMuted),
                          ),
                        ],
                      ),
                    )
                  : ListView.separated(
                      controller: controller,
                      padding: const EdgeInsets.symmetric(
                          horizontal: AppSpacing.pagePadding,
                          vertical: AppSpacing.sm),
                      itemCount: reminders.length,
                      separatorBuilder: (_, __) =>
                          Divider(height: 1, color: ctx.colBorder),
                      itemBuilder: (ctx2, idx) {
                        final r = reminders[idx];
                        return Padding(
                          padding:
                              const EdgeInsets.symmetric(vertical: AppSpacing.sm),
                          child: Row(
                            children: [
                              Container(
                                width: 36,
                                height: 36,
                                decoration: BoxDecoration(
                                  color:
                                      r.color.withValues(alpha: 0.15),
                                  borderRadius: BorderRadius.circular(
                                      AppSpacing.radiusMd),
                                ),
                                child: Icon(r.icon,
                                    size: 18, color: r.color),
                              ),
                              const SizedBox(width: AppSpacing.sm),
                              Expanded(
                                child: Column(
                                  crossAxisAlignment:
                                      CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      r.plantName,
                                      style: AppTypography.labelLarge(ctx2)
                                          .copyWith(fontSize: 13),
                                    ),
                                    Text(
                                      r.message,
                                      style:
                                          AppTypography.bodySmall(ctx2)
                                              .copyWith(
                                                  color: r.isUrgent
                                                      ? r.color
                                                      : ctx2.colTextSecondary),
                                    ),
                                  ],
                                ),
                              ),
                              if (r.isUrgent)
                                Container(
                                  padding: const EdgeInsets.symmetric(
                                      horizontal: 6, vertical: 2),
                                  decoration: BoxDecoration(
                                    color:
                                        r.color.withValues(alpha: 0.15),
                                    borderRadius: BorderRadius.circular(
                                        AppSpacing.radiusFull),
                                  ),
                                  child: Text(
                                    '!',
                                    style: AppTypography.labelSmall(ctx2)
                                        .copyWith(
                                            color: r.color,
                                            fontWeight: FontWeight.bold),
                                  ),
                                ),
                            ],
                          ),
                        );
                      },
                    ),
            ),
          ],
        ),
      ),
    );
  }
}

// Reminder logic + view-models live in lib/utils/home_reminders.dart.

// ── Space card ────────────────────────────────────

class _SpaceCard extends StatefulWidget {
  final GrowSpace space;
  final List<Plant> plants;
  final double? latestTemp;
  final double? latestHumidity;
  final bool? isOptimal;
  final DateTime? latestRecordedAt;

  const _SpaceCard({
    super.key,
    required this.space,
    required this.plants,
    this.latestTemp,
    this.latestHumidity,
    this.isOptimal,
    this.latestRecordedAt,
  });

  @override
  State<_SpaceCard> createState() => _SpaceCardState();
}

class _SpaceCardState extends State<_SpaceCard> {
  bool _expanded = true;

  void _showQuickLogDialog(BuildContext context) {
    final repo = context.read<GrowRepository>();
    final tempCtrl = TextEditingController();
    final humidityCtrl = TextEditingController();

    showModalBottomSheet<void>(
      context: context,
      isScrollControlled: true,
      backgroundColor: Colors.transparent,
      builder: (ctx) => AppSheet(
        title: 'Quick Log',
        subtitle: widget.space.name,
        icon: Icons.thermostat_rounded,
        iconColor: AppColors.water,
        children: [
          // Temperature
          TextField(
            controller: tempCtrl,
            autofocus: true,
            keyboardType:
                const TextInputType.numberWithOptions(decimal: true),
            style: TextStyle(color: ctx.colTextPrimary),
            decoration: InputDecoration(
              labelText: tempUnitLabel,
              prefixIcon: const Icon(Icons.thermostat_rounded),
            ),
          ),
          const SizedBox(height: AppSpacing.sm),
          // Humidity
          TextField(
            controller: humidityCtrl,
            keyboardType:
                const TextInputType.numberWithOptions(decimal: true),
            style: TextStyle(color: ctx.colTextPrimary),
            decoration: const InputDecoration(
              labelText: 'Humidity (%)',
              prefixIcon: Icon(Icons.water_drop_rounded),
            ),
          ),
          const SizedBox(height: AppSpacing.lg),
          // Action
          SizedBox(
            width: double.infinity,
            child: ElevatedButton.icon(
              icon: const Icon(Icons.add_rounded, size: 18),
              label: const Text('Save Log'),
              style: ElevatedButton.styleFrom(
                backgroundColor: AppColors.primary,
                foregroundColor: Colors.black,
                padding: const EdgeInsets.symmetric(vertical: 14),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
                ),
              ),
              onPressed: () {
                final rawTemp = double.tryParse(tempCtrl.text);
                final humidity = double.tryParse(humidityCtrl.text);
                if (rawTemp == null && humidity == null) return;
                repo.addEnvironmentLog(EnvironmentLog(
                  id: repo.newId(),
                  growSpaceId: widget.space.id,
                  recordedAt: DateTime.now(),
                  temperature:
                      rawTemp != null ? toStorageTemp(rawTemp) : null,
                  humidity: humidity,
                ));
                Navigator.pop(ctx);
                AppToast.show(
                  context,
                  'Logged to ${widget.space.name}',
                  type: ToastType.info,
                  duration: const Duration(milliseconds: 2000),
                );
              },
            ),
          ),
          const SizedBox(height: AppSpacing.xs),
          TextButton(
            onPressed: () => Navigator.pop(ctx),
            child: Text('Cancel',
                style: AppTypography.labelLarge(ctx)
                    .copyWith(color: ctx.colTextSecondary)),
          ),
        ],
      ),
    ).then((_) {
      tempCtrl.dispose();
      humidityCtrl.dispose();
    });
  }

  @override
  Widget build(BuildContext context) {
    final envColor = widget.isOptimal == null
        ? context.colTextMuted
        : widget.isOptimal!
            ? AppColors.optimal
            : AppColors.warning;

    return AppCard(
      padding: EdgeInsets.zero,
      child: Column(
        children: [
          // ── Space header ─────────────────────
          GestureDetector(
            onTap: () => Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) =>
                    space_screen.SpaceDetailScreen(space: widget.space),
              ),
            ),
            child: Container(
              padding: const EdgeInsets.all(AppSpacing.cardPadding),
              decoration: BoxDecoration(
                gradient: LinearGradient(
                  begin: Alignment.topLeft,
                  end: Alignment.bottomRight,
                  colors: [
                    envColor.withValues(alpha: 0.08),
                    context.colSurface1,
                  ],
                ),
                borderRadius: BorderRadius.vertical(
                  top: const Radius.circular(AppSpacing.radiusLg),
                  bottom: _expanded
                      ? Radius.zero
                      : const Radius.circular(AppSpacing.radiusLg),
                ),
              ),
              child: Row(
                children: [
                  // Env indicator dot
                  Container(
                    width: 10,
                    height: 10,
                    margin: const EdgeInsets.only(right: AppSpacing.sm),
                    decoration: BoxDecoration(
                      shape: BoxShape.circle,
                      color: envColor,
                      boxShadow: [
                        BoxShadow(
                          color: envColor.withValues(alpha: 0.5),
                          blurRadius: 6,
                        ),
                      ],
                    ),
                  ),

                  // Bug fix v2: the env readout (temp + humidity +
                  // age) used to sit as a SIBLING of the Expanded
                  // name column.  On the S22 with long space names
                  // and the two trailing icon-buttons (nutrient
                  // calc + batch care) this caused 49-60 px of
                  // horizontal overflow.  Moving the env readout
                  // BELOW the name row inside the Expanded column
                  // gives us the full card width for environment
                  // chips instead of fighting for the same row.
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(widget.space.name,
                            style: AppTypography.headlineSmall(context),
                            maxLines: 1,
                            overflow: TextOverflow.ellipsis),
                        const SizedBox(height: 2),
                        Row(children: [
                          Flexible(
                            child: Text(widget.space.type,
                                style: AppTypography.bodySmall(context),
                                maxLines: 1,
                                overflow: TextOverflow.ellipsis),
                          ),
                          const SizedBox(width: AppSpacing.xs),
                          Text('·', style: AppTypography.bodySmall(context)),
                          const SizedBox(width: AppSpacing.xs),
                          Text(
                            '${widget.plants.length} plant${widget.plants.length == 1 ? '' : 's'}',
                            style: AppTypography.bodySmall(context)
                                .copyWith(color: AppColors.primary),
                          ),
                          if (widget.latestTemp != null ||
                              widget.latestHumidity != null) ...[
                            const SizedBox(width: AppSpacing.sm),
                            if (widget.latestTemp != null) ...[
                              Icon(Icons.thermostat,
                                  size: 13, color: envColor),
                              const SizedBox(width: 2),
                              Text(
                                formatTemp(widget.latestTemp!, decimals: 0),
                                style: AppTypography.bodySmall(context)
                                    .copyWith(color: envColor),
                              ),
                              const SizedBox(width: AppSpacing.xs),
                            ],
                            if (widget.latestHumidity != null) ...[
                              Icon(Icons.water_drop,
                                  size: 13, color: envColor),
                              const SizedBox(width: 2),
                              Text(
                                '${widget.latestHumidity!.toStringAsFixed(0)}%',
                                style: AppTypography.bodySmall(context)
                                    .copyWith(color: envColor),
                              ),
                            ],
                          ],
                        ]),
                      ],
                    ),
                  ),

                  // Nutrient calculator shortcut
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: () {
                      // Pre-fill from the most recently started active plant
                      // in this space so the suggestion is immediately useful.
                      final candidates = widget.plants
                          .where((p) => p.medium != null || p.growStage != null)
                          .toList()
                        ..sort((a, b) => b.startDate.compareTo(a.startDate));
                      final ref = candidates.isNotEmpty ? candidates.first : null;
                      Navigator.push(
                        context,
                        MaterialPageRoute(
                          builder: (_) => NutrientCalculatorScreen(
                            initialMedium: ref?.medium,
                            initialStage: ref?.growStage,
                          ),
                        ),
                      );
                    },
                    child: Padding(
                      padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xxs, vertical: AppSpacing.xs),
                      child: Icon(Icons.science_rounded,
                          size: 18, color: context.colTextMuted),
                    ),
                  ),

                  // Batch care button — only shown when the space has plants.
                  if (widget.plants.isNotEmpty)
                    GestureDetector(
                      behavior: HitTestBehavior.opaque,
                      onTap: () {
                        final repo = context.read<GrowRepository>();
                        BatchCareSheet.show(
                          context,
                          space: widget.space,
                          plants: widget.plants,
                          allNotes: repo.notes
                              .where((n) => widget.plants
                                  .any((p) => p.id == n.plantId))
                              .toList(),
                        );
                      },
                      child: Padding(
                        padding: const EdgeInsets.symmetric(horizontal: AppSpacing.xxs, vertical: AppSpacing.xs),
                        child: Icon(Icons.water_drop_outlined,
                            size: 18, color: context.colTextMuted),
                      ),
                    ),

                  // Quick env-log button — GestureDetector with opaque
                  // behaviour stops the tap propagating to the nav handler.
                  GestureDetector(
                    behavior: HitTestBehavior.opaque,
                    onTap: () => _showQuickLogDialog(context),
                    child: Padding(
                      padding:
                          const EdgeInsets.symmetric(horizontal: AppSpacing.xxs, vertical: AppSpacing.xs),
                      child: Icon(Icons.thermostat_outlined,
                          size: 18, color: context.colTextMuted),
                    ),
                  ),

                  // Expand toggle
                  GestureDetector(
                    onTap: () => setState(() => _expanded = !_expanded),
                    child: AnimatedRotation(
                      turns: _expanded ? 0 : -0.25,
                      duration: const Duration(milliseconds: 200),
                      child: Icon(
                        Icons.keyboard_arrow_down,
                        color: context.colTextMuted,
                        size: 22,
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ),

          // ── Plants list ──────────────────────
          AnimatedCrossFade(
            duration: const Duration(milliseconds: 250),
            crossFadeState: _expanded
                ? CrossFadeState.showFirst
                : CrossFadeState.showSecond,
            firstChild: widget.plants.isEmpty
                ? Padding(
                    padding: const EdgeInsets.all(AppSpacing.md),
                    child: Text(
                      AppLocalizations.of(context).homeNoPlantsYet,
                      style: AppTypography.bodyMedium(context)
                          .copyWith(fontStyle: FontStyle.italic),
                    ),
                  )
                : Column(
                    children: widget.plants
                        .map((p) => _PlantRow(
                              plant: p,
                              siblings: widget.plants,
                            ))
                        .toList(),
                  ),
            secondChild: const SizedBox.shrink(),
          ),
        ],
      ),
    );
  }
}

// ── Plant row inside space card ───────────────────

class _PlantRow extends StatelessWidget {
  final Plant plant;
  final List<Plant>? siblings;

  const _PlantRow({required this.plant, this.siblings});

  void _showCareSheet(
    BuildContext context,
    Plant plant,
    CareStatus waterStatus,
    CareStatus feedStatus,
    CareStatus ipmStatus,
  ) {
    final items = <({String label, IconData icon, Color color, CareStatus status})>[];
    if (plant.wateringReminderEnabled) {
      items.add((
        label: 'Watering',
        icon: Icons.water_drop_rounded,
        color: AppColors.water,
        status: waterStatus,
      ));
    }
    if (plant.feedingReminderEnabled) {
      items.add((
        label: 'Feeding',
        icon: Icons.eco_rounded,
        color: AppColors.accent,
        status: feedStatus,
      ));
    }
    if (plant.ipmReminderEnabled) {
      items.add((
        label: 'IPM Spray',
        icon: Icons.bug_report_rounded,
        color: AppColors.ipmColor,
        status: ipmStatus,
      ));
    }

    showModalBottomSheet<void>(
      context: context,
      backgroundColor: Colors.transparent,
      builder: (ctx) => AppSheet(
        title: plant.name,
        subtitle: 'Care status',
        children: [
            ...items.map((item) {
              final statusLabel = switch (item.status) {
                CareStatus.overdue  => 'Overdue',
                CareStatus.dueSoon  => 'Due soon',
                CareStatus.ok       => 'On track',
              };
              final statusColor = switch (item.status) {
                CareStatus.overdue  => AppColors.danger,
                CareStatus.dueSoon  => AppColors.warning,
                CareStatus.ok       => AppColors.primary,
              };
              return Padding(
                padding: const EdgeInsets.only(bottom: AppSpacing.sm),
                child: Row(
                  children: [
                    Container(
                      width: 32, height: 32,
                      decoration: BoxDecoration(
                        color: item.color.withValues(alpha: 0.12),
                        borderRadius:
                            BorderRadius.circular(AppSpacing.radiusSm),
                      ),
                      child:
                          Icon(item.icon, size: 15, color: item.color),
                    ),
                    const SizedBox(width: AppSpacing.sm),
                    Expanded(
                      child: Text(item.label,
                          style: AppTypography.bodyMedium(ctx)),
                    ),
                    Container(
                      padding: const EdgeInsets.symmetric(
                          horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: statusColor.withValues(alpha: 0.12),
                        borderRadius: BorderRadius.circular(
                            AppSpacing.radiusFull),
                      ),
                      child: Text(
                        statusLabel,
                        style: AppTypography.labelSmall(ctx).copyWith(
                            color: statusColor, fontSize: 11),
                      ),
                    ),
                  ],
                ),
              );
            }),
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    final color = AppColors.statusColor(plant.statusLabel);
    final needsBurp = plant.status == PlantStatus.curing &&
        plant.burpingRemindersEnabled;

    final repo = context.read<GrowRepository>();
    final plantNotes = repo.notesForPlant(plant.id);
    // F10 — same stage-adjusted intervals as the home reminder bell.
    final waterStatus = computeCareStatus(
      enabled: plant.wateringReminderEnabled,
      plantStatus: plant.status,
      startDate: plant.startDate,
      intervalDays: plant.effectiveWateringIntervalDays(),
      notes: plantNotes,
      plantId: plant.id,
      category: NoteCategory.watering,
    );
    final feedStatus = computeCareStatus(
      enabled: plant.feedingReminderEnabled,
      plantStatus: plant.status,
      startDate: plant.startDate,
      intervalDays: plant.effectiveFeedingIntervalDays(),
      notes: plantNotes,
      plantId: plant.id,
      category: NoteCategory.feeding,
    );
    final ipmStatus = computeCareStatus(
      enabled: plant.ipmReminderEnabled,
      plantStatus: plant.status,
      startDate: plant.startDate,
      intervalDays: plant.effectiveIpmIntervalDays(),
      notes: plantNotes,
      plantId: plant.id,
      category: NoteCategory.ipm,
    );

    // Summarise all care statuses into one badge to avoid row crowding.
    final careStatuses = [waterStatus, feedStatus, ipmStatus];
    final anyOverdue = careStatuses.any((s) => s == CareStatus.overdue);
    final anyDueSoon = careStatuses.any((s) => s == CareStatus.dueSoon);
    final showCareBadge = anyOverdue || anyDueSoon;
    final badgeColor = anyOverdue ? AppColors.danger : AppColors.warning;

    return InkWell(
      onTap: () => Navigator.push(
        context,
        MaterialPageRoute(
          builder: (_) =>
              PlantDetailScreen(plant: plant, siblings: siblings),
        ),
      ),
      child: Container(
        padding: const EdgeInsets.symmetric(
          horizontal: AppSpacing.md,
          vertical: AppSpacing.sm,
        ),
        decoration: BoxDecoration(
          border: Border(top: BorderSide(color: context.colBorderFaint)),
        ),
        child: Row(
          children: [
            // UX9 — thumbnail-or-status avatar.  Uses the most recent
            // note photo as a rounded thumb when one exists; otherwise
            // falls back to the original status-colour disc.  The
            // status colour still bleeds through via the border so the
            // status signal isn't lost when a photo is present.
            _PlantAvatar(
              plant: plant,
              notes: plantNotes,
              statusColor: color,
            ),
            const SizedBox(width: AppSpacing.sm),

            // Name + strain
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(plant.name,
                      style: AppTypography.bodyLarge(context)
                          .copyWith(fontWeight: FontWeight.w600)),
                  Text(plant.strain, style: AppTypography.bodySmall(context)),
                ],
              ),
            ),

            // Grow stage pill — visible only for actively growing plants
            if (plant.status == PlantStatus.growing &&
                plant.growStage != null) ...[
              Container(
                margin: const EdgeInsets.only(right: AppSpacing.xs),
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: BoxDecoration(
                  color: AppColors.growing.withValues(alpha: 0.12),
                  borderRadius:
                      BorderRadius.circular(AppSpacing.radiusFull),
                  border: Border.all(
                      color: AppColors.growing.withValues(alpha: 0.35)),
                ),
                child: Text(
                  plant.growStage!.shortLabel,
                  style: AppTypography.labelSmall(context)
                      .copyWith(color: AppColors.growing, fontSize: 10),
                ),
              ),
            ],

            // Phase-aware day counter
            Text(
              plant.statusDaysLabel,
              style: AppTypography.bodySmall(context)
                  .copyWith(color: context.colTextMuted),
            ),
            const SizedBox(width: AppSpacing.sm),

            // Combined care badge — tap to see per-category breakdown
            if (showCareBadge) ...[
              GestureDetector(
                onTap: () => _showCareSheet(context, plant, waterStatus,
                    feedStatus, ipmStatus),
                child: Container(
                  padding: const EdgeInsets.symmetric(
                      horizontal: 5, vertical: 2),
                  decoration: BoxDecoration(
                    color: badgeColor.withValues(alpha: 0.15),
                    borderRadius:
                        BorderRadius.circular(AppSpacing.radiusFull),
                    border: Border.all(
                        color: badgeColor.withValues(alpha: 0.4)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(Icons.priority_high_rounded,
                          size: 10, color: badgeColor),
                      const SizedBox(width: 2),
                      Text(
                        anyOverdue ? 'Overdue' : 'Due soon',
                        style: AppTypography.labelSmall(context).copyWith(
                            color: badgeColor, fontSize: 9),
                      ),
                    ],
                  ),
                ),
              ),
              const SizedBox(width: AppSpacing.xs),
            ],

            // Burping reminder chip — visible when curing reminders are on
            if (needsBurp) ...[
              Container(
                padding: const EdgeInsets.symmetric(
                    horizontal: 6, vertical: 2),
                decoration: BoxDecoration(
                  color: AppColors.curing.withValues(alpha: 0.15),
                  borderRadius:
                      BorderRadius.circular(AppSpacing.radiusFull),
                  border: Border.all(
                      color: AppColors.curing.withValues(alpha: 0.4)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    const Icon(Icons.air_rounded,
                        size: 10, color: AppColors.curing),
                    const SizedBox(width: 3),
                    Text(
                      'Burp',
                      style: AppTypography.labelSmall(context)
                          .copyWith(
                              color: AppColors.curing, fontSize: 9),
                    ),
                  ],
                ),
              ),
              const SizedBox(width: AppSpacing.xs),
            ],

            StatusBadge.fromStatus(plant.statusLabel, small: true),
            const SizedBox(width: AppSpacing.xs),
            Icon(Icons.chevron_right,
                size: 16, color: context.colTextMuted),
          ],
        ),
      ),
    );
  }
}

// ── Home empty state ──────────────────────────────────────────────────────────

class _HomeEmptyState extends StatelessWidget {
  const _HomeEmptyState();

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.fromLTRB(
        AppSpacing.pagePadding,
        AppSpacing.xl,
        AppSpacing.pagePadding,
        120, // clear FAB
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // ── Hero ───────────────────────────
          // A3 — potted-seedling line-art instead of the
          // eco_rounded-in-circle icon.  Larger size (104) so the
          // hero carries the otherwise text-heavy "what you'll
          // unlock" section that follows.
          Center(
            child: Column(
              children: [
                const LineArtIllustration(art: EmptyArt.plant, size: 104),
                const SizedBox(height: AppSpacing.md),
                Text(
                  AppLocalizations.of(context).homeEmptyTitle,
                  style: AppTypography.headlineLarge(context)
                      .copyWith(color: AppColors.primary),
                  textAlign: TextAlign.center,
                ),
                const SizedBox(height: AppSpacing.xs),
                Text(
                  AppLocalizations.of(context).homeEmptySubtitle,
                  style: AppTypography.bodyMedium(context)
                      .copyWith(color: context.colTextMuted),
                  textAlign: TextAlign.center,
                ),
              ],
            ),
          ),

          const SizedBox(height: AppSpacing.xl),

          // ── What gets unlocked ──────────────
          Text(
            'What you\'ll unlock',
            style: AppTypography.headlineSmall(context),
          ),
          const SizedBox(height: AppSpacing.sm),

          const _UnlockRow(
            icon: Icons.thermostat_rounded,
            color: AppColors.drying,
            title: 'Environment monitoring',
            body:
                'Log temp, humidity & VPD per space. Get alerted when conditions drift out of range.',
          ),
          const _UnlockRow(
            icon: Icons.eco_rounded,
            color: AppColors.growing,
            title: 'Per-plant grow journal',
            body:
                'Track every watering, feeding, training, and observation from seed to cure.',
          ),
          const _UnlockRow(
            icon: Icons.event_repeat_rounded,
            color: AppColors.secondary,
            title: 'Space-wide care schedules',
            body:
                'Set watering, feeding & IPM intervals per space. See what\'s due today in the 7-day strip.',
          ),
          const _UnlockRow(
            icon: Icons.insights_rounded,
            color: AppColors.primary,
            title: 'Yield analytics & strain intelligence',
            body:
                'After your first harvest: strain leaderboard, yield trends, and grow-over-grow comparison.',
          ),
          const _UnlockRow(
            icon: Icons.archive_rounded,
            color: AppColors.harvested,
            title: 'Harvest archive with grow reports',
            body:
                'Every completed run generates a full report — duration, yield, quality, and notes.',
          ),

          const SizedBox(height: AppSpacing.xl),

          // ── FAB nudge ───────────────────────
          Container(
            padding: const EdgeInsets.all(AppSpacing.md),
            decoration: BoxDecoration(
              color: AppColors.primary.withValues(alpha: 0.06),
              borderRadius: BorderRadius.circular(AppSpacing.radiusMd),
              border: Border.all(
                  color: AppColors.primary.withValues(alpha: 0.2)),
            ),
            child: Row(
              children: [
                Container(
                  width: 40,
                  height: 40,
                  decoration: BoxDecoration(
                    color: AppColors.primary,
                    borderRadius:
                        BorderRadius.circular(AppSpacing.radiusSm),
                  ),
                  child: const Icon(Icons.add, color: Colors.black, size: 22),
                ),
                const SizedBox(width: AppSpacing.md),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text('Tap the + button',
                          style: AppTypography.labelLarge(context)),
                      Text(
                        'Bottom right → Add Space to get started',
                        style: AppTypography.bodySmall(context)
                            .copyWith(color: context.colTextMuted),
                      ),
                    ],
                  ),
                ),
                const Icon(Icons.south_east_rounded,
                    color: AppColors.primary, size: 20),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

class _UnlockRow extends StatelessWidget {
  final IconData icon;
  final Color color;
  final String title;
  final String body;

  const _UnlockRow({
    required this.icon,
    required this.color,
    required this.title,
    required this.body,
  });

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: AppSpacing.sm),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Container(
            width: 36,
            height: 36,
            margin: const EdgeInsets.only(top: 2),
            decoration: BoxDecoration(
              color: color.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
            ),
            child: Icon(icon, color: color, size: 18),
          ),
          const SizedBox(width: AppSpacing.sm),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text(title,
                    style: AppTypography.labelLarge(context)
                        .copyWith(fontSize: 13)),
                const SizedBox(height: 2),
                Text(body,
                    style: AppTypography.bodySmall(context)
                        .copyWith(color: context.colTextMuted)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// UX9 — Plant tile thumbnail avatar
// ─────────────────────────────────────────────────────────────────────────────

/// 32×32 avatar shown at the leading edge of a [_PlantRow].
///
/// When the plant has at least one note photo, the most recent one is
/// shown as a tinted thumbnail with a [statusColor] border.  When no
/// photo is on file the avatar falls back to a solid [statusColor]
/// disc — the same visual signal the row used before.
///
/// Built as a `StatelessWidget` so it can be reused from anywhere a
/// compact plant identity affordance is needed (Notes tab, Archive
/// search results, etc.).
class _PlantAvatar extends StatelessWidget {
  final Plant plant;
  final List<PlantNote> notes;
  final Color statusColor;

  const _PlantAvatar({
    required this.plant,
    required this.notes,
    required this.statusColor,
  });

  /// Most-recent photo filename across all of the plant's notes, or
  /// null when none exist.  Notes are already sorted newest-first by
  /// `GrowRepository.notesForPlant`, so we just take the first match.
  String? _mostRecentPhoto() {
    for (final n in notes) {
      if (n.photoUrls.isNotEmpty) return n.photoUrls.first;
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final photo = _mostRecentPhoto();
    // Photo path is resolved via [PhotoPathResolver] so the stored
    // filename works regardless of whether the user reinstalled (a
    // legacy absolute path stays valid; a bare filename gets prepended
    // with the current Documents directory).
    if (photo != null) {
      return Container(
        width: 32,
        height: 32,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
          // Status colour shows through as a 1.5px outer ring so the
          // signal isn't lost just because there's a thumbnail.
          border: Border.all(color: statusColor, width: 1.5),
        ),
        clipBehavior: Clip.antiAlias,
        child: Image.file(
          File(PhotoPathResolver.resolve(photo)),
          fit: BoxFit.cover,
          // P1.4 — 32 px logical thumbnail.  Without this cap a fresh
          // iPhone photo decodes at native 4032 × 3024 just to fill
          // this 32 × 32 disc.
          cacheWidth: imageCacheWidth(context, 32),
          // A9 — the plant card already announces plant name + status
          // via its surrounding Text widgets, so this 32 px thumbnail
          // is purely decorative.  Excluding it stops TalkBack from
          // injecting a redundant "image" node before the row label.
          excludeFromSemantics: true,
          // If the file vanished (manual delete, OS storage reclaim)
          // we silently degrade to the same disc fallback as no-photo.
          errorBuilder: (_, __, ___) => _StatusDisc(color: statusColor),
        ),
      );
    }
    return _StatusDisc(color: statusColor);
  }
}

/// Solid-colour rounded-square fallback used when the plant has no
/// note photos.  Slightly larger than the previous 8px dot so it
/// visually balances the rows that DO have a photo thumbnail.
class _StatusDisc extends StatelessWidget {
  final Color color;
  const _StatusDisc({required this.color});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 32,
      height: 32,
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.18),
        borderRadius: BorderRadius.circular(AppSpacing.radiusSm),
        border: Border.all(color: color, width: 1.5),
      ),
      alignment: Alignment.center,
      child: Icon(Icons.eco_rounded, size: 16, color: color),
    );
  }
}

