"""i18n round 3 (task #176) — append plantDetail* keys to the 8 non-English ARBs.

One-shot migration helper.  Translations follow the terminology already
established in each locale's status* / settingsNotif* keys (e.g. Afrikaans
"veroudering" for curing, French "affinage", Italian "concia") so the new
strings read consistently with the rest of the app.

Run from repo root:  python tools/add_plant_detail_arb.py
Idempotent: skips a locale if plantDetailHarvestPlant already exists.
"""
import io
import json
import os

L = {
 "es": {
  "plantDetailHarvestPlant": "Cosechar planta",
  "plantDetailWetWeightHeader": "PESO HÚMEDO  ·  OPCIONAL",
  "plantDetailWetWeightLabel": "Peso húmedo (g) — deja en blanco para omitir",
  "plantDetailWetWeightHelper": "Omite si solo pesas tras el secado",
  "plantDetailHarvestDateHeader": "FECHA DE COSECHA",
  "plantDetailStartDrying": "Iniciar secado",
  "plantDetailEstimatedDryDateHeader": "FECHA ESTIMADA DE SECADO",
  "plantDetailCompleteDrying": "Completar secado",
  "plantDetailDryWeightHeader": "PESO SECO",
  "plantDetailDryWeightLabel": "Peso seco (g)",
  "plantDetailDryingEndDateHeader": "FIN DEL SECADO (OPCIONAL)",
  "plantDetailSetEndDateOptional": "Definir fecha de fin (opcional)",
  "plantDetailStartCuring": "Iniciar curado",
  "plantDetailPhotoJournal": "Diario fotográfico",
  "plantDetailNoPhotosYet": "Aún sin fotos",
  "plantDetailPhotoCount": "{count, plural, =1{1 foto} other{{count} fotos}}",
  "plantDetailNoteDeletedTitle": "Nota eliminada",
  "plantDetailNoteDeletedSubtitle": "La nota se ha eliminado\npermanentemente de esta planta.",
  "plantDetailEditPlantTooltip": "Editar planta",
  "plantDetailAddNoteTooltip": "Añadir nota",
  "plantDetailTakeClonesTooltip": "Tomar esquejes",
  "plantDetailGrowReportTooltip": "Informe de cultivo",
  "plantDetailCompareStrains": "Comparar variedades",
  "plantDetailCloneOrigin": "Propagada por esqueje — comparte la genética de la planta madre.",
  "plantDetailSeedOrigin": "Cultivada desde semilla — tiene su propia expresión genética.",
  "plantDetailMotherSummary": "{count, plural, =1{Esta planta es madre — se ha tomado 1 esqueje registrado como planta independiente.} other{Esta planta es madre — se han tomado {count} esquejes registrados como plantas independientes.}}",
  "plantDetailTargetHarvestReached": "Fecha objetivo de cosecha alcanzada",
  "plantDetailPlantRemoved": "Esta planta fue eliminada.",
  "plantDetailDayOfFlower": "Día {day} de floración",
  "plantDetailWateredAgo": "Regada hace {days}d",
  "plantDetailFedAgo": "Fertilizada hace {days}d",
  "plantDetailTrainedAgo": "Entrenada hace {days}d",
  "plantDetailHeightTall": "{cm} cm de altura",
  "plantDetailYieldInsights": "Análisis de rendimiento",
  "plantDetailYieldInsightsSubtitle": "Proyección + cálculo de peso seco",
  "plantDetailCommunityBenchmark": "Comparativa comunitaria",
  "plantDetailCommunityBenchmarkSubtitle": "Compara con rendimientos anónimos de la comunidad",
  "plantDetailHealthScore": "Índice de salud",
  "plantDetailHealthScoreSubtitle": "Problemas, ambiente y frecuencia de cuidados",
  "plantDetailEnvironmentSection": "Ambiente",
  "plantDetailEnvironmentSectionSubtitle": "Temp / humedad / DPV en el tiempo",
  "plantDetailNutrientTrends": "Tendencias de nutrientes y pH",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K de los registros de fertilización",
  "plantDetailHeightTracker": "Registro de altura",
  "plantDetailHeightTrackerSubtitle": "Curva de crecimiento desde las notas de medición",
  "plantDetailDaysGrowing": "Días\ncultivo",
  "plantDetailDaysDrying": "Días\nsecado",
  "plantDetailDaysCuring": "Días\ncurado",
  "plantDetailOverdue": "Atrasado",
  "plantDetailLeft": "Restante",
  "plantDetailSinceDate": "desde {date}",
  "plantDetailUntilDate": "hasta {date}",
  "plantDetailHarvestCta": "Cosechar",
  "plantDetailCompleteCure": "Completar curado",
  "plantDetailLifecycleComplete": "Ciclo completado",
  "plantDetailViewReport": "Ver informe",
  "plantDetailMove": "Mover",
  "plantDetailCull": "Descartar",
  "plantDetailPlantTimeline": "Cronología de la planta",
  "plantDetailNotesCount": "Notas ({count})",
  "plantDetailNotesFiltered": "Notas ({shown}/{total})",
  "plantDetailTemplates": "Plantillas",
  "plantDetailNoNotes": "Sin notas — toca Añadir para empezar",
  "plantDetailNoCategoryNotes": "Aún no hay notas de {category}",
  "plantDetailMarkResolved": "Marcar como resuelto",
  "plantDetailResolve": "Resolver",
  "plantDetailResolved": "Resuelto",
  "plantDetailNoteProduct": "Producto",
  "plantDetailNoteVolume": "Volumen",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Enmiendas",
  "plantDetailNotePhIn": "pH entrada",
  "plantDetailNoteRunoffPh": "pH drenaje",
  "plantDetailNoteTarget": "Objetivo",
  "plantDetailNoteMethod": "Método",
  "plantDetailNoteDilution": "Dilución",
 },
 "de": {
  "plantDetailHarvestPlant": "Pflanze ernten",
  "plantDetailWetWeightHeader": "NASSGEWICHT  ·  OPTIONAL",
  "plantDetailWetWeightLabel": "Nassgewicht (g) — leer lassen zum Überspringen",
  "plantDetailWetWeightHelper": "Überspringen, wenn du erst nach dem Trocknen wiegst",
  "plantDetailHarvestDateHeader": "ERNTEDATUM",
  "plantDetailStartDrying": "Trocknung starten",
  "plantDetailEstimatedDryDateHeader": "VORAUSSICHTLICHES TROCKNUNGSENDE",
  "plantDetailCompleteDrying": "Trocknung abschließen",
  "plantDetailDryWeightHeader": "TROCKENGEWICHT",
  "plantDetailDryWeightLabel": "Trockengewicht (g)",
  "plantDetailDryingEndDateHeader": "TROCKNUNGSENDE (OPTIONAL)",
  "plantDetailSetEndDateOptional": "Enddatum festlegen (optional)",
  "plantDetailStartCuring": "Aushärtung starten",
  "plantDetailPhotoJournal": "Foto-Tagebuch",
  "plantDetailNoPhotosYet": "Noch keine Fotos",
  "plantDetailPhotoCount": "{count, plural, =1{1 Foto} other{{count} Fotos}}",
  "plantDetailNoteDeletedTitle": "Notiz gelöscht",
  "plantDetailNoteDeletedSubtitle": "Die Notiz wurde dauerhaft\nvon dieser Pflanze entfernt.",
  "plantDetailEditPlantTooltip": "Pflanze bearbeiten",
  "plantDetailAddNoteTooltip": "Notiz hinzufügen",
  "plantDetailTakeClonesTooltip": "Stecklinge nehmen",
  "plantDetailGrowReportTooltip": "Grow-Bericht",
  "plantDetailCompareStrains": "Sorten vergleichen",
  "plantDetailCloneOrigin": "Aus einem Steckling vermehrt — teilt die Genetik der Mutterpflanze.",
  "plantDetailSeedOrigin": "Aus Samen gezogen — hat eine eigene genetische Ausprägung.",
  "plantDetailMotherSummary": "{count, plural, =1{Diese Pflanze ist eine Mutter — 1 Steckling wurde genommen und als eigene Pflanze erfasst.} other{Diese Pflanze ist eine Mutter — {count} Stecklinge wurden genommen und als eigene Pflanzen erfasst.}}",
  "plantDetailTargetHarvestReached": "Ziel-Erntedatum erreicht",
  "plantDetailPlantRemoved": "Diese Pflanze wurde entfernt.",
  "plantDetailDayOfFlower": "Blütetag {day}",
  "plantDetailWateredAgo": "Gegossen vor {days} T.",
  "plantDetailFedAgo": "Gedüngt vor {days} T.",
  "plantDetailTrainedAgo": "Trainiert vor {days} T.",
  "plantDetailHeightTall": "{cm} cm hoch",
  "plantDetailYieldInsights": "Ertragsanalyse",
  "plantDetailYieldInsightsSubtitle": "Prognose + Trockengewicht-Berechnung",
  "plantDetailCommunityBenchmark": "Community-Vergleich",
  "plantDetailCommunityBenchmarkSubtitle": "Mit anonymen Community-Erträgen vergleichen",
  "plantDetailHealthScore": "Gesundheitswert",
  "plantDetailHealthScoreSubtitle": "Probleme, Umgebung & Pflegefrequenz",
  "plantDetailEnvironmentSection": "Umgebung",
  "plantDetailEnvironmentSectionSubtitle": "Temp. / Luftfeuchte / VPD im Zeitverlauf",
  "plantDetailNutrientTrends": "Nährstoff- & pH-Trends",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K aus den Düngeprotokollen",
  "plantDetailHeightTracker": "Höhenverlauf",
  "plantDetailHeightTrackerSubtitle": "Wachstumskurve aus den Messnotizen",
  "plantDetailDaysGrowing": "Tage\nWachstum",
  "plantDetailDaysDrying": "Tage\nTrocknung",
  "plantDetailDaysCuring": "Tage\nAushärtung",
  "plantDetailOverdue": "Überfällig",
  "plantDetailLeft": "Übrig",
  "plantDetailSinceDate": "seit {date}",
  "plantDetailUntilDate": "bis {date}",
  "plantDetailHarvestCta": "Ernten",
  "plantDetailCompleteCure": "Aushärtung abschließen",
  "plantDetailLifecycleComplete": "Zyklus abgeschlossen",
  "plantDetailViewReport": "Bericht ansehen",
  "plantDetailMove": "Verschieben",
  "plantDetailCull": "Aussortieren",
  "plantDetailPlantTimeline": "Pflanzen-Zeitachse",
  "plantDetailNotesCount": "Notizen ({count})",
  "plantDetailNotesFiltered": "Notizen ({shown}/{total})",
  "plantDetailTemplates": "Vorlagen",
  "plantDetailNoNotes": "Keine Notizen — tippe auf Hinzufügen",
  "plantDetailNoCategoryNotes": "Noch keine {category}-Notizen",
  "plantDetailMarkResolved": "Als gelöst markieren",
  "plantDetailResolve": "Lösen",
  "plantDetailResolved": "Gelöst",
  "plantDetailNoteProduct": "Produkt",
  "plantDetailNoteVolume": "Volumen",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Zusätze",
  "plantDetailNotePhIn": "pH zu",
  "plantDetailNoteRunoffPh": "Ablauf-pH",
  "plantDetailNoteTarget": "Ziel",
  "plantDetailNoteMethod": "Methode",
  "plantDetailNoteDilution": "Verdünnung",
 },
 "fr": {
  "plantDetailHarvestPlant": "Récolter la plante",
  "plantDetailWetWeightHeader": "POIDS HUMIDE  ·  FACULTATIF",
  "plantDetailWetWeightLabel": "Poids humide (g) — laisser vide pour passer",
  "plantDetailWetWeightHelper": "Passe si tu ne pèses qu'après séchage",
  "plantDetailHarvestDateHeader": "DATE DE RÉCOLTE",
  "plantDetailStartDrying": "Démarrer le séchage",
  "plantDetailEstimatedDryDateHeader": "FIN DE SÉCHAGE ESTIMÉE",
  "plantDetailCompleteDrying": "Terminer le séchage",
  "plantDetailDryWeightHeader": "POIDS SEC",
  "plantDetailDryWeightLabel": "Poids sec (g)",
  "plantDetailDryingEndDateHeader": "FIN DU SÉCHAGE (FACULTATIF)",
  "plantDetailSetEndDateOptional": "Définir la date de fin (facultatif)",
  "plantDetailStartCuring": "Démarrer l'affinage",
  "plantDetailPhotoJournal": "Journal photo",
  "plantDetailNoPhotosYet": "Pas encore de photos",
  "plantDetailPhotoCount": "{count, plural, =1{1 photo} other{{count} photos}}",
  "plantDetailNoteDeletedTitle": "Note supprimée",
  "plantDetailNoteDeletedSubtitle": "La note a été définitivement\nsupprimée de cette plante.",
  "plantDetailEditPlantTooltip": "Modifier la plante",
  "plantDetailAddNoteTooltip": "Ajouter une note",
  "plantDetailTakeClonesTooltip": "Prélever des boutures",
  "plantDetailGrowReportTooltip": "Rapport de culture",
  "plantDetailCompareStrains": "Comparer les variétés",
  "plantDetailCloneOrigin": "Issue d'une bouture — partage la génétique de la plante mère.",
  "plantDetailSeedOrigin": "Issue d'une graine — possède sa propre expression génétique.",
  "plantDetailMotherSummary": "{count, plural, =1{Cette plante est une mère — 1 bouture a été prélevée et suivie comme plante distincte.} other{Cette plante est une mère — {count} boutures ont été prélevées et suivies comme plantes distinctes.}}",
  "plantDetailTargetHarvestReached": "Date de récolte cible atteinte",
  "plantDetailPlantRemoved": "Cette plante a été retirée.",
  "plantDetailDayOfFlower": "Jour {day} de floraison",
  "plantDetailWateredAgo": "Arrosée il y a {days} j",
  "plantDetailFedAgo": "Nourrie il y a {days} j",
  "plantDetailTrainedAgo": "Palissée il y a {days} j",
  "plantDetailHeightTall": "{cm} cm de haut",
  "plantDetailYieldInsights": "Analyse du rendement",
  "plantDetailYieldInsightsSubtitle": "Projection + calcul du poids sec",
  "plantDetailCommunityBenchmark": "Comparatif communautaire",
  "plantDetailCommunityBenchmarkSubtitle": "Compare aux rendements anonymes de la communauté",
  "plantDetailHealthScore": "Score de santé",
  "plantDetailHealthScoreSubtitle": "Problèmes, environnement et fréquence des soins",
  "plantDetailEnvironmentSection": "Environnement",
  "plantDetailEnvironmentSectionSubtitle": "Temp / humidité / DPV dans le temps",
  "plantDetailNutrientTrends": "Tendances nutriments & pH",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K des journaux de fertilisation",
  "plantDetailHeightTracker": "Suivi de hauteur",
  "plantDetailHeightTrackerSubtitle": "Courbe de croissance issue des notes de mesure",
  "plantDetailDaysGrowing": "Jours\ncroissance",
  "plantDetailDaysDrying": "Jours\nséchage",
  "plantDetailDaysCuring": "Jours\naffinage",
  "plantDetailOverdue": "En retard",
  "plantDetailLeft": "Restant",
  "plantDetailSinceDate": "depuis {date}",
  "plantDetailUntilDate": "jusqu'au {date}",
  "plantDetailHarvestCta": "Récolter",
  "plantDetailCompleteCure": "Terminer l'affinage",
  "plantDetailLifecycleComplete": "Cycle terminé",
  "plantDetailViewReport": "Voir le rapport",
  "plantDetailMove": "Déplacer",
  "plantDetailCull": "Éliminer",
  "plantDetailPlantTimeline": "Chronologie de la plante",
  "plantDetailNotesCount": "Notes ({count})",
  "plantDetailNotesFiltered": "Notes ({shown}/{total})",
  "plantDetailTemplates": "Modèles",
  "plantDetailNoNotes": "Aucune note — touche Ajouter pour commencer",
  "plantDetailNoCategoryNotes": "Pas encore de notes {category}",
  "plantDetailMarkResolved": "Marquer comme résolu",
  "plantDetailResolve": "Résoudre",
  "plantDetailResolved": "Résolu",
  "plantDetailNoteProduct": "Produit",
  "plantDetailNoteVolume": "Volume",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Amendements",
  "plantDetailNotePhIn": "pH entrée",
  "plantDetailNoteRunoffPh": "pH drainage",
  "plantDetailNoteTarget": "Cible",
  "plantDetailNoteMethod": "Méthode",
  "plantDetailNoteDilution": "Dilution",
 },
 "pt": {
  "plantDetailHarvestPlant": "Colher planta",
  "plantDetailWetWeightHeader": "PESO ÚMIDO  ·  OPCIONAL",
  "plantDetailWetWeightLabel": "Peso úmido (g) — deixe em branco para pular",
  "plantDetailWetWeightHelper": "Pule se você só pesa após a secagem",
  "plantDetailHarvestDateHeader": "DATA DA COLHEITA",
  "plantDetailStartDrying": "Iniciar secagem",
  "plantDetailEstimatedDryDateHeader": "FIM ESTIMADO DA SECAGEM",
  "plantDetailCompleteDrying": "Concluir secagem",
  "plantDetailDryWeightHeader": "PESO SECO",
  "plantDetailDryWeightLabel": "Peso seco (g)",
  "plantDetailDryingEndDateHeader": "FIM DA SECAGEM (OPCIONAL)",
  "plantDetailSetEndDateOptional": "Definir data de término (opcional)",
  "plantDetailStartCuring": "Iniciar cura",
  "plantDetailPhotoJournal": "Diário fotográfico",
  "plantDetailNoPhotosYet": "Ainda sem fotos",
  "plantDetailPhotoCount": "{count, plural, =1{1 foto} other{{count} fotos}}",
  "plantDetailNoteDeletedTitle": "Nota excluída",
  "plantDetailNoteDeletedSubtitle": "A nota foi removida\npermanentemente desta planta.",
  "plantDetailEditPlantTooltip": "Editar planta",
  "plantDetailAddNoteTooltip": "Adicionar nota",
  "plantDetailTakeClonesTooltip": "Tirar clones",
  "plantDetailGrowReportTooltip": "Relatório de cultivo",
  "plantDetailCompareStrains": "Comparar variedades",
  "plantDetailCloneOrigin": "Propagada por estaca — compartilha a genética da planta-mãe.",
  "plantDetailSeedOrigin": "Cultivada de semente — tem expressão genética própria.",
  "plantDetailMotherSummary": "{count, plural, =1{Esta planta é uma mãe — 1 clone foi tirado e registrado como planta separada.} other{Esta planta é uma mãe — {count} clones foram tirados e registrados como plantas separadas.}}",
  "plantDetailTargetHarvestReached": "Data-alvo de colheita atingida",
  "plantDetailPlantRemoved": "Esta planta foi removida.",
  "plantDetailDayOfFlower": "Dia {day} de floração",
  "plantDetailWateredAgo": "Regada há {days}d",
  "plantDetailFedAgo": "Fertilizada há {days}d",
  "plantDetailTrainedAgo": "Treinada há {days}d",
  "plantDetailHeightTall": "{cm} cm de altura",
  "plantDetailYieldInsights": "Análise de rendimento",
  "plantDetailYieldInsightsSubtitle": "Projeção + cálculo de peso seco",
  "plantDetailCommunityBenchmark": "Comparativo da comunidade",
  "plantDetailCommunityBenchmarkSubtitle": "Compare com rendimentos anônimos da comunidade",
  "plantDetailHealthScore": "Índice de saúde",
  "plantDetailHealthScoreSubtitle": "Problemas, ambiente e frequência de cuidados",
  "plantDetailEnvironmentSection": "Ambiente",
  "plantDetailEnvironmentSectionSubtitle": "Temp / umidade / DPV ao longo do tempo",
  "plantDetailNutrientTrends": "Tendências de nutrientes e pH",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K dos registros de fertilização",
  "plantDetailHeightTracker": "Registro de altura",
  "plantDetailHeightTrackerSubtitle": "Curva de crescimento das notas de medição",
  "plantDetailDaysGrowing": "Dias\ncultivo",
  "plantDetailDaysDrying": "Dias\nsecagem",
  "plantDetailDaysCuring": "Dias\ncura",
  "plantDetailOverdue": "Atrasado",
  "plantDetailLeft": "Restante",
  "plantDetailSinceDate": "desde {date}",
  "plantDetailUntilDate": "até {date}",
  "plantDetailHarvestCta": "Colher",
  "plantDetailCompleteCure": "Concluir cura",
  "plantDetailLifecycleComplete": "Ciclo concluído",
  "plantDetailViewReport": "Ver relatório",
  "plantDetailMove": "Mover",
  "plantDetailCull": "Descartar",
  "plantDetailPlantTimeline": "Linha do tempo da planta",
  "plantDetailNotesCount": "Notas ({count})",
  "plantDetailNotesFiltered": "Notas ({shown}/{total})",
  "plantDetailTemplates": "Modelos",
  "plantDetailNoNotes": "Sem notas — toque em Adicionar para começar",
  "plantDetailNoCategoryNotes": "Ainda não há notas de {category}",
  "plantDetailMarkResolved": "Marcar como resolvido",
  "plantDetailResolve": "Resolver",
  "plantDetailResolved": "Resolvido",
  "plantDetailNoteProduct": "Produto",
  "plantDetailNoteVolume": "Volume",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Aditivos",
  "plantDetailNotePhIn": "pH entrada",
  "plantDetailNoteRunoffPh": "pH drenagem",
  "plantDetailNoteTarget": "Alvo",
  "plantDetailNoteMethod": "Método",
  "plantDetailNoteDilution": "Diluição",
 },
 "it": {
  "plantDetailHarvestPlant": "Raccogli pianta",
  "plantDetailWetWeightHeader": "PESO UMIDO  ·  FACOLTATIVO",
  "plantDetailWetWeightLabel": "Peso umido (g) — lascia vuoto per saltare",
  "plantDetailWetWeightHelper": "Salta se pesi solo dopo l'essiccazione",
  "plantDetailHarvestDateHeader": "DATA DI RACCOLTA",
  "plantDetailStartDrying": "Avvia essiccazione",
  "plantDetailEstimatedDryDateHeader": "FINE ESSICCAZIONE STIMATA",
  "plantDetailCompleteDrying": "Completa essiccazione",
  "plantDetailDryWeightHeader": "PESO SECCO",
  "plantDetailDryWeightLabel": "Peso secco (g)",
  "plantDetailDryingEndDateHeader": "FINE ESSICCAZIONE (FACOLTATIVO)",
  "plantDetailSetEndDateOptional": "Imposta data di fine (facoltativo)",
  "plantDetailStartCuring": "Avvia concia",
  "plantDetailPhotoJournal": "Diario fotografico",
  "plantDetailNoPhotosYet": "Ancora nessuna foto",
  "plantDetailPhotoCount": "{count, plural, =1{1 foto} other{{count} foto}}",
  "plantDetailNoteDeletedTitle": "Nota eliminata",
  "plantDetailNoteDeletedSubtitle": "La nota è stata rimossa\ndefinitivamente da questa pianta.",
  "plantDetailEditPlantTooltip": "Modifica pianta",
  "plantDetailAddNoteTooltip": "Aggiungi nota",
  "plantDetailTakeClonesTooltip": "Preleva talee",
  "plantDetailGrowReportTooltip": "Report di coltivazione",
  "plantDetailCompareStrains": "Confronta varietà",
  "plantDetailCloneOrigin": "Propagata da talea — condivide la genetica della pianta madre.",
  "plantDetailSeedOrigin": "Nata da seme — ha una propria espressione genetica.",
  "plantDetailMotherSummary": "{count, plural, =1{Questa pianta è una madre — 1 talea è stata prelevata e tracciata come pianta separata.} other{Questa pianta è una madre — {count} talee sono state prelevate e tracciate come piante separate.}}",
  "plantDetailTargetHarvestReached": "Data di raccolta obiettivo raggiunta",
  "plantDetailPlantRemoved": "Questa pianta è stata rimossa.",
  "plantDetailDayOfFlower": "Giorno {day} di fioritura",
  "plantDetailWateredAgo": "Annaffiata {days} g fa",
  "plantDetailFedAgo": "Concimata {days} g fa",
  "plantDetailTrainedAgo": "Addestrata {days} g fa",
  "plantDetailHeightTall": "{cm} cm di altezza",
  "plantDetailYieldInsights": "Analisi della resa",
  "plantDetailYieldInsightsSubtitle": "Proiezione + calcolo del peso secco",
  "plantDetailCommunityBenchmark": "Confronto community",
  "plantDetailCommunityBenchmarkSubtitle": "Confronta con le rese anonime della community",
  "plantDetailHealthScore": "Indice di salute",
  "plantDetailHealthScoreSubtitle": "Problemi, ambiente e frequenza delle cure",
  "plantDetailEnvironmentSection": "Ambiente",
  "plantDetailEnvironmentSectionSubtitle": "Temp / umidità / VPD nel tempo",
  "plantDetailNutrientTrends": "Tendenze nutrienti e pH",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K dai registri di concimazione",
  "plantDetailHeightTracker": "Tracciamento altezza",
  "plantDetailHeightTrackerSubtitle": "Curva di crescita dalle note di misurazione",
  "plantDetailDaysGrowing": "Giorni\ncrescita",
  "plantDetailDaysDrying": "Giorni\nessiccazione",
  "plantDetailDaysCuring": "Giorni\nconcia",
  "plantDetailOverdue": "In ritardo",
  "plantDetailLeft": "Rimanenti",
  "plantDetailSinceDate": "dal {date}",
  "plantDetailUntilDate": "fino al {date}",
  "plantDetailHarvestCta": "Raccogli",
  "plantDetailCompleteCure": "Completa concia",
  "plantDetailLifecycleComplete": "Ciclo completato",
  "plantDetailViewReport": "Vedi report",
  "plantDetailMove": "Sposta",
  "plantDetailCull": "Scarta",
  "plantDetailPlantTimeline": "Cronologia della pianta",
  "plantDetailNotesCount": "Note ({count})",
  "plantDetailNotesFiltered": "Note ({shown}/{total})",
  "plantDetailTemplates": "Modelli",
  "plantDetailNoNotes": "Nessuna nota — tocca Aggiungi per iniziare",
  "plantDetailNoCategoryNotes": "Ancora nessuna nota {category}",
  "plantDetailMarkResolved": "Segna come risolto",
  "plantDetailResolve": "Risolvi",
  "plantDetailResolved": "Risolto",
  "plantDetailNoteProduct": "Prodotto",
  "plantDetailNoteVolume": "Volume",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Additivi",
  "plantDetailNotePhIn": "pH ingresso",
  "plantDetailNoteRunoffPh": "pH drenaggio",
  "plantDetailNoteTarget": "Bersaglio",
  "plantDetailNoteMethod": "Metodo",
  "plantDetailNoteDilution": "Diluizione",
 },
 "nl": {
  "plantDetailHarvestPlant": "Plant oogsten",
  "plantDetailWetWeightHeader": "NAT GEWICHT  ·  OPTIONEEL",
  "plantDetailWetWeightLabel": "Nat gewicht (g) — leeg laten om over te slaan",
  "plantDetailWetWeightHelper": "Sla over als je alleen na het drogen weegt",
  "plantDetailHarvestDateHeader": "OOGSTDATUM",
  "plantDetailStartDrying": "Drogen starten",
  "plantDetailEstimatedDryDateHeader": "GESCHATTE DROOGDATUM",
  "plantDetailCompleteDrying": "Drogen afronden",
  "plantDetailDryWeightHeader": "DROOG GEWICHT",
  "plantDetailDryWeightLabel": "Droog gewicht (g)",
  "plantDetailDryingEndDateHeader": "EINDE DROGEN (OPTIONEEL)",
  "plantDetailSetEndDateOptional": "Einddatum instellen (optioneel)",
  "plantDetailStartCuring": "Curing starten",
  "plantDetailPhotoJournal": "Fotodagboek",
  "plantDetailNoPhotosYet": "Nog geen foto's",
  "plantDetailPhotoCount": "{count, plural, =1{1 foto} other{{count} foto's}}",
  "plantDetailNoteDeletedTitle": "Notitie verwijderd",
  "plantDetailNoteDeletedSubtitle": "De notitie is permanent\nvan deze plant verwijderd.",
  "plantDetailEditPlantTooltip": "Plant bewerken",
  "plantDetailAddNoteTooltip": "Notitie toevoegen",
  "plantDetailTakeClonesTooltip": "Stekken nemen",
  "plantDetailGrowReportTooltip": "Kweekrapport",
  "plantDetailCompareStrains": "Soorten vergelijken",
  "plantDetailCloneOrigin": "Gestekt van een moederplant — deelt dezelfde genetica.",
  "plantDetailSeedOrigin": "Gekweekt uit zaad — heeft een eigen genetische expressie.",
  "plantDetailMotherSummary": "{count, plural, =1{Deze plant is een moeder — 1 stek is genomen en als aparte plant geregistreerd.} other{Deze plant is een moeder — {count} stekken zijn genomen en als aparte planten geregistreerd.}}",
  "plantDetailTargetHarvestReached": "Geplande oogstdatum bereikt",
  "plantDetailPlantRemoved": "Deze plant is verwijderd.",
  "plantDetailDayOfFlower": "Dag {day} van de bloei",
  "plantDetailWateredAgo": "{days}d geleden water gegeven",
  "plantDetailFedAgo": "{days}d geleden gevoed",
  "plantDetailTrainedAgo": "{days}d geleden getraind",
  "plantDetailHeightTall": "{cm} cm hoog",
  "plantDetailYieldInsights": "Opbrengstanalyse",
  "plantDetailYieldInsightsSubtitle": "Projectie + droog-gewichtberekening",
  "plantDetailCommunityBenchmark": "Community-vergelijking",
  "plantDetailCommunityBenchmarkSubtitle": "Vergelijk met anonieme community-opbrengsten",
  "plantDetailHealthScore": "Gezondheidsscore",
  "plantDetailHealthScoreSubtitle": "Problemen, omgeving & verzorgingsfrequentie",
  "plantDetailEnvironmentSection": "Omgeving",
  "plantDetailEnvironmentSectionSubtitle": "Temp / vochtigheid / VPD in de tijd",
  "plantDetailNutrientTrends": "Voedings- & pH-trends",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K uit de voedingslogs",
  "plantDetailHeightTracker": "Hoogtetracker",
  "plantDetailHeightTrackerSubtitle": "Groeicurve uit de meetnotities",
  "plantDetailDaysGrowing": "Dagen\ngroei",
  "plantDetailDaysDrying": "Dagen\ndrogen",
  "plantDetailDaysCuring": "Dagen\ncuring",
  "plantDetailOverdue": "Te laat",
  "plantDetailLeft": "Resterend",
  "plantDetailSinceDate": "sinds {date}",
  "plantDetailUntilDate": "tot {date}",
  "plantDetailHarvestCta": "Oogsten",
  "plantDetailCompleteCure": "Curing afronden",
  "plantDetailLifecycleComplete": "Cyclus voltooid",
  "plantDetailViewReport": "Rapport bekijken",
  "plantDetailMove": "Verplaatsen",
  "plantDetailCull": "Verwijderen",
  "plantDetailPlantTimeline": "Planttijdlijn",
  "plantDetailNotesCount": "Notities ({count})",
  "plantDetailNotesFiltered": "Notities ({shown}/{total})",
  "plantDetailTemplates": "Sjablonen",
  "plantDetailNoNotes": "Geen notities — tik op Toevoegen om te beginnen",
  "plantDetailNoCategoryNotes": "Nog geen {category}-notities",
  "plantDetailMarkResolved": "Markeren als opgelost",
  "plantDetailResolve": "Oplossen",
  "plantDetailResolved": "Opgelost",
  "plantDetailNoteProduct": "Product",
  "plantDetailNoteVolume": "Volume",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Toevoegingen",
  "plantDetailNotePhIn": "pH in",
  "plantDetailNoteRunoffPh": "Afvoer-pH",
  "plantDetailNoteTarget": "Doel",
  "plantDetailNoteMethod": "Methode",
  "plantDetailNoteDilution": "Verdunning",
 },
 "af": {
  "plantDetailHarvestPlant": "Oes plant",
  "plantDetailWetWeightHeader": "NAT GEWIG  ·  OPSIONEEL",
  "plantDetailWetWeightLabel": "Nat gewig (g) — los leeg om oor te slaan",
  "plantDetailWetWeightHelper": "Slaan oor as jy eers ná droging weeg",
  "plantDetailHarvestDateHeader": "OESDATUM",
  "plantDetailStartDrying": "Begin droging",
  "plantDetailEstimatedDryDateHeader": "GESKATTE DROOGDATUM",
  "plantDetailCompleteDrying": "Voltooi droging",
  "plantDetailDryWeightHeader": "DROË GEWIG",
  "plantDetailDryWeightLabel": "Droë gewig (g)",
  "plantDetailDryingEndDateHeader": "EINDE VAN DROGING (OPSIONEEL)",
  "plantDetailSetEndDateOptional": "Stel einddatum (opsioneel)",
  "plantDetailStartCuring": "Begin veroudering",
  "plantDetailPhotoJournal": "Fotojoernaal",
  "plantDetailNoPhotosYet": "Nog geen foto's nie",
  "plantDetailPhotoCount": "{count, plural, =1{1 foto} other{{count} foto's}}",
  "plantDetailNoteDeletedTitle": "Nota verwyder",
  "plantDetailNoteDeletedSubtitle": "Die nota is permanent\nvan hierdie plant verwyder.",
  "plantDetailEditPlantTooltip": "Wysig plant",
  "plantDetailAddNoteTooltip": "Voeg nota by",
  "plantDetailTakeClonesTooltip": "Neem steggies",
  "plantDetailGrowReportTooltip": "Kweekverslag",
  "plantDetailCompareStrains": "Vergelyk variëteite",
  "plantDetailCloneOrigin": "Voortgeplant uit 'n steggie — deel die moederplant se genetika.",
  "plantDetailSeedOrigin": "Uit saad gekweek — het sy eie genetiese uitdrukking.",
  "plantDetailMotherSummary": "{count, plural, =1{Hierdie plant is 'n moeder — 1 steggie is geneem en as aparte plant aangeteken.} other{Hierdie plant is 'n moeder — {count} steggies is geneem en as aparte plante aangeteken.}}",
  "plantDetailTargetHarvestReached": "Teiken-oesdatum bereik",
  "plantDetailPlantRemoved": "Hierdie plant is verwyder.",
  "plantDetailDayOfFlower": "Dag {day} van blom",
  "plantDetailWateredAgo": "Natgemaak {days}d gelede",
  "plantDetailFedAgo": "Gevoer {days}d gelede",
  "plantDetailTrainedAgo": "Opgelei {days}d gelede",
  "plantDetailHeightTall": "{cm} cm hoog",
  "plantDetailYieldInsights": "Opbrengs-insigte",
  "plantDetailYieldInsightsSubtitle": "Projeksie + droë-gewig berekening",
  "plantDetailCommunityBenchmark": "Gemeenskapsvergelyking",
  "plantDetailCommunityBenchmarkSubtitle": "Vergelyk met anonieme gemeenskapsopbrengste",
  "plantDetailHealthScore": "Gesondheidstelling",
  "plantDetailHealthScoreSubtitle": "Probleme, omgewing & versorgingsfrekwensie",
  "plantDetailEnvironmentSection": "Omgewing",
  "plantDetailEnvironmentSectionSubtitle": "Temp / humiditeit / VPD oor tyd",
  "plantDetailNutrientTrends": "Voedingstof- & pH-tendense",
  "plantDetailNutrientTrendsSubtitle": "EC / pH / N-P-K uit voedingsrekords",
  "plantDetailHeightTracker": "Hoogtemeter",
  "plantDetailHeightTrackerSubtitle": "Groeikurwe uit metingnotas",
  "plantDetailDaysGrowing": "Dae\ngroei",
  "plantDetailDaysDrying": "Dae\ndroging",
  "plantDetailDaysCuring": "Dae\nveroudering",
  "plantDetailOverdue": "Agterstallig",
  "plantDetailLeft": "Oor",
  "plantDetailSinceDate": "sedert {date}",
  "plantDetailUntilDate": "tot {date}",
  "plantDetailHarvestCta": "Oes",
  "plantDetailCompleteCure": "Voltooi veroudering",
  "plantDetailLifecycleComplete": "Lewensiklus voltooi",
  "plantDetailViewReport": "Bekyk verslag",
  "plantDetailMove": "Skuif",
  "plantDetailCull": "Verwyder",
  "plantDetailPlantTimeline": "Plant-tydlyn",
  "plantDetailNotesCount": "Notas ({count})",
  "plantDetailNotesFiltered": "Notas ({shown}/{total})",
  "plantDetailTemplates": "Sjablone",
  "plantDetailNoNotes": "Geen notas nie — tik Voeg by om te begin",
  "plantDetailNoCategoryNotes": "Nog geen {category}-notas nie",
  "plantDetailMarkResolved": "Merk as opgelos",
  "plantDetailResolve": "Los op",
  "plantDetailResolved": "Opgelos",
  "plantDetailNoteProduct": "Produk",
  "plantDetailNoteVolume": "Volume",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Byvoegings",
  "plantDetailNotePhIn": "pH in",
  "plantDetailNoteRunoffPh": "Afloop-pH",
  "plantDetailNoteTarget": "Teiken",
  "plantDetailNoteMethod": "Metode",
  "plantDetailNoteDilution": "Verdunning",
 },
 "zu": {
  "plantDetailHarvestPlant": "Vuna isitshalo",
  "plantDetailWetWeightHeader": "ISISINDO ESIMANZI  ·  OKUZIKHETHELA",
  "plantDetailWetWeightLabel": "Isisindo esimanzi (g) — shiya kungenalutho ukweqa",
  "plantDetailWetWeightHelper": "Yeqa uma ukala kuphela ngemva kokoma",
  "plantDetailHarvestDateHeader": "USUKU LOKUVUNA",
  "plantDetailStartDrying": "Qala ukomisa",
  "plantDetailEstimatedDryDateHeader": "USUKU OKULINDELEKE UKOMA NGALO",
  "plantDetailCompleteDrying": "Qedela ukomisa",
  "plantDetailDryWeightHeader": "ISISINDO ESOMILE",
  "plantDetailDryWeightLabel": "Isisindo esomile (g)",
  "plantDetailDryingEndDateHeader": "UKUPHELA KOKOMISA (OKUZIKHETHELA)",
  "plantDetailSetEndDateOptional": "Setha usuku lokuphela (okuzikhethela)",
  "plantDetailStartCuring": "Qala ukuvuthwa",
  "plantDetailPhotoJournal": "Ijenali yezithombe",
  "plantDetailNoPhotosYet": "Azikho izithombe okwamanje",
  "plantDetailPhotoCount": "{count, plural, =1{isithombe esi-1} other{izithombe ezingu-{count}}}",
  "plantDetailNoteDeletedTitle": "Inothi lisusiwe",
  "plantDetailNoteDeletedSubtitle": "Inothi lisuswe unomphela\nkulesi sitshalo.",
  "plantDetailEditPlantTooltip": "Hlela isitshalo",
  "plantDetailAddNoteTooltip": "Engeza inothi",
  "plantDetailTakeClonesTooltip": "Thatha izithombo",
  "plantDetailGrowReportTooltip": "Umbiko wokutshala",
  "plantDetailCompareStrains": "Qhathanisa izinhlobo",
  "plantDetailCloneOrigin": "Sakhiwe ngesithombo — sabelana ngofuzo lwesitshalo esingumama.",
  "plantDetailSeedOrigin": "Siqale ngembewu — sinofuzo lwaso oluzimele.",
  "plantDetailMotherSummary": "{count, plural, =1{Lesi sitshalo singumama — kuthathwe isithombo esi-1 salandelelwa njengesitshalo esizimele.} other{Lesi sitshalo singumama — kuthathwe izithombo ezingu-{count} zalandelelwa njengezitshalo ezizimele.}}",
  "plantDetailTargetHarvestReached": "Usuku oluhlosiwe lokuvuna selufikile",
  "plantDetailPlantRemoved": "Lesi sitshalo sasusiwe.",
  "plantDetailDayOfFlower": "Usuku {day} lokuqhakaza",
  "plantDetailWateredAgo": "Saniselwa ezinsukwini ezingu-{days} ezedlule",
  "plantDetailFedAgo": "Sondliwe ezinsukwini ezingu-{days} ezedlule",
  "plantDetailTrainedAgo": "Saqeqeshwa ezinsukwini ezingu-{days} ezedlule",
  "plantDetailHeightTall": "Ubude obungu-{cm} cm",
  "plantDetailYieldInsights": "Ukuhlaziywa kwesivuno",
  "plantDetailYieldInsightsSubtitle": "Isilinganiso + izibalo zesisindo esomile",
  "plantDetailCommunityBenchmark": "Ukuqhathanisa nomphakathi",
  "plantDetailCommunityBenchmarkSubtitle": "Qhathanisa nezivuno zomphakathi ezingaziwa",
  "plantDetailHealthScore": "Amaphuzu empilo",
  "plantDetailHealthScoreSubtitle": "Izinkinga, imvelo nokuvama kokunakekela",
  "plantDetailEnvironmentSection": "Imvelo",
  "plantDetailEnvironmentSectionSubtitle": "Izinga lokushisa / umswakama / i-VPD ngokuhamba kwesikhathi",
  "plantDetailNutrientTrends": "Izitayela zezakhamzimba ne-pH",
  "plantDetailNutrientTrendsSubtitle": "I-EC / pH / N-P-K kusuka kumarekhodi okondla",
  "plantDetailHeightTracker": "Isilandeleli sobude",
  "plantDetailHeightTrackerSubtitle": "Ijika lokukhula kusuka kumanothi okukala",
  "plantDetailDaysGrowing": "Izinsuku\nzokukhula",
  "plantDetailDaysDrying": "Izinsuku\nzokoma",
  "plantDetailDaysCuring": "Izinsuku\nzokuvuthwa",
  "plantDetailOverdue": "Sekudlulile",
  "plantDetailLeft": "Okusele",
  "plantDetailSinceDate": "kusukela {date}",
  "plantDetailUntilDate": "kuze kube {date}",
  "plantDetailHarvestCta": "Vuna",
  "plantDetailCompleteCure": "Qedela ukuvuthwa",
  "plantDetailLifecycleComplete": "Umjikelezo uphelile",
  "plantDetailViewReport": "Buka umbiko",
  "plantDetailMove": "Hambisa",
  "plantDetailCull": "Susa",
  "plantDetailPlantTimeline": "Uhlu lwezehlakalo zesitshalo",
  "plantDetailNotesCount": "Amanothi ({count})",
  "plantDetailNotesFiltered": "Amanothi ({shown}/{total})",
  "plantDetailTemplates": "Amathempulethi",
  "plantDetailNoNotes": "Awekho amanothi — thepha u-Engeza ukuqala",
  "plantDetailNoCategoryNotes": "Awekho amanothi e-{category} okwamanje",
  "plantDetailMarkResolved": "Maka njengokuxazululiwe",
  "plantDetailResolve": "Xazulula",
  "plantDetailResolved": "Kuxazululiwe",
  "plantDetailNoteProduct": "Umkhiqizo",
  "plantDetailNoteVolume": "Ivolumu",
  "plantDetailNoteNpk": "NPK",
  "plantDetailNoteAmendments": "Izengezo",
  "plantDetailNotePhIn": "I-pH engenayo",
  "plantDetailNoteRunoffPh": "I-pH ephumayo",
  "plantDetailNoteTarget": "Okuhlosiwe",
  "plantDetailNoteMethod": "Indlela",
  "plantDetailNoteDilution": "Ukuhlanganiswa namanzi",
 },
}


def main() -> None:
    base = os.path.join("lib", "l10n")
    for locale, entries in L.items():
        path = os.path.join(base, f"app_{locale}.arb")
        with io.open(path, encoding="utf-8") as f:
            data = json.load(f)
        if "plantDetailHarvestPlant" in data:
            print(f"skip {path} (already migrated)")
            continue
        with io.open(path, encoding="utf-8") as f:
            text = f.read().rstrip()
        assert text.endswith("}")
        body = ",\n".join(
            f'  "{k}": {json.dumps(v, ensure_ascii=False)}'
            for k, v in entries.items()
        )
        text = text[: text.rfind("}")].rstrip().rstrip(",")
        text += ",\n\n" + body + "\n}\n"
        json.loads(text)  # validate before writing
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote {len(entries)} keys -> {path}")


if __name__ == "__main__":
    main()
