"""i18n round 3 part 2 (task #176) — append spaceDetail* keys to the 8
non-English ARBs.  Same conventions as add_plant_detail_arb.py: terminology
follows each locale's established status*/settingsNotif* keys.

Run from repo root:  python tools/add_space_detail_arb.py
Idempotent: skips a locale if spaceDetailEditSpace already exists.
"""
import io
import json
import os

L = {
 "es": {
  "spaceDetailEditSpace": "Editar espacio",
  "spaceDetailEditSpaceSubtitle": "Actualiza nombre, tipo y equipamiento",
  "spaceDetailSpaceNameLabel": "Nombre del espacio *",
  "spaceDetailTypeLabel": "Tipo",
  "spaceDetailNotesOptionalLabel": "Notas (opcional)",
  "spaceDetailHardwareOptional": "Equipamiento (opcional)",
  "spaceDetailWattageLabel": "Potencia",
  "spaceDetailAreaLabel": "Superficie",
  "spaceDetailSaveChanges": "Guardar cambios",
  "spaceDetailSpaceUpdatedToast": "Espacio actualizado",
  "spaceDetailHumidityPctLabel": "Humedad (%)",
  "spaceDetailSaveReading": "Guardar lectura",
  "spaceDetailEnterTempOrHumidity": "Introduce al menos un valor de temperatura o humedad",
  "spaceDetailOptimal": "Óptimo",
  "spaceDetailCheck": "Revisar",
  "spaceDetailNoData": "Sin datos",
  "spaceDetailIdealRange": "Ideal {range}",
  "spaceDetailDeleteSpaceTitle": "¿Eliminar \"{name}\"?",
  "spaceDetailCannotBeUndone": "Esta acción no se puede deshacer.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 planta activa se archivará como eliminada.} other{{count} plantas activas se archivarán como eliminadas.}}",
  "spaceDetailDeleteSpace": "Eliminar espacio",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" eliminado · 1 planta archivada} other{\"{name}\" eliminado · {count} plantas archivadas}}",
  "spaceDetailDeleted": "\"{name}\" eliminado",
  "spaceDetailViewPlantTimelineTooltip": "Ver cronología de plantas",
  "spaceDetailNutrientCalculatorTooltip": "Calculadora de nutrientes",
  "spaceDetailLogCareAllTooltip": "Registrar cuidados para todas las plantas",
  "spaceDetailCurrentConditions": "Condiciones actuales",
  "spaceDetailLastReading": "Última lectura: {date}",
  "spaceDetailNoReadingsYet": "Aún sin lecturas registradas",
  "spaceDetailTemperature": "Temperatura",
  "spaceDetailHumidity": "Humedad",
  "spaceDetailViewFullAnalytics": "Ver análisis completo",
  "spaceDetailAnalyticsSubtitle": "desglose por fase · DPV · rachas",
  "spaceDetailThresholdsSaved": "Umbrales guardados",
  "spaceDetailLightCalculator": "Calculadora de luz",
  "spaceDetailLightCalcSubtitle": "Calcula la integral de luz diaria a partir del PPFD y el fotoperiodo.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Fotoperiodo",
  "spaceDetailStage": "Fase",
  "spaceDetailHours": "Horas",
  "spaceDetailStageSeedling": "Plántula",
  "spaceDetailStageVegetative": "Vegetativo",
  "spaceDetailStageFlowering": "Floración",
  "spaceDetailStageLateFlower": "Floración tardía",
  "spaceDetailDliTooLow": "Muy bajo",
  "spaceDetailDliTooHigh": "Muy alto",
  "spaceDetailSeedlingDli": "DLI plántula",
  "spaceDetailVegetativeDli": "DLI vegetativo",
  "spaceDetailFloweringDli": "DLI floración",
  "spaceDetailHistoryCount": "Historial ({count})",
  "spaceDetailNoReadingsEmpty": "Aún sin lecturas\nToca Registrar Ambiente para empezar",
  "spaceDetailLogEntryDeleted": "Registro eliminado",
  "spaceDetailLogEntryDeletedSubtitle": "El registro de ambiente\nse ha eliminado.",
  "spaceDetailShowLess": "Mostrar menos",
  "spaceDetailShowAllReadings": "Mostrar las {count} lecturas",
  "spaceDetailCareScheduleSaved": "Calendario de cuidados guardado",
  "spaceDetailEveryNDays": "{count, plural, =1{Cada día} other{Cada {count} días}}",
  "spaceDetailCareSchedule": "Calendario de cuidados",
  "spaceDetailSpaceWide": "Todo el espacio",
  "spaceDetailOneScheduleAll": "Un calendario para todas las plantas de este espacio.",
  "spaceDetailWatering": "Riego",
  "spaceDetailFeeding": "Fertilización",
  "spaceDetailIpmInspection": "MIP / Inspección de plagas",
  "spaceDetailSaveSchedule": "Guardar calendario",
  "spaceDetailPlantsCount": "Plantas ({count})",
 },
 "de": {
  "spaceDetailEditSpace": "Bereich bearbeiten",
  "spaceDetailEditSpaceSubtitle": "Name, Typ & Ausstattung anpassen",
  "spaceDetailSpaceNameLabel": "Bereichsname *",
  "spaceDetailTypeLabel": "Typ",
  "spaceDetailNotesOptionalLabel": "Notizen (optional)",
  "spaceDetailHardwareOptional": "Ausstattung (optional)",
  "spaceDetailWattageLabel": "Leistung",
  "spaceDetailAreaLabel": "Fläche",
  "spaceDetailSaveChanges": "Änderungen speichern",
  "spaceDetailSpaceUpdatedToast": "Bereich aktualisiert",
  "spaceDetailHumidityPctLabel": "Luftfeuchte (%)",
  "spaceDetailSaveReading": "Messung speichern",
  "spaceDetailEnterTempOrHumidity": "Gib mindestens Temperatur oder Luftfeuchte ein",
  "spaceDetailOptimal": "Optimal",
  "spaceDetailCheck": "Prüfen",
  "spaceDetailNoData": "Keine Daten",
  "spaceDetailIdealRange": "Ideal {range}",
  "spaceDetailDeleteSpaceTitle": "\"{name}\" löschen?",
  "spaceDetailCannotBeUndone": "Diese Aktion kann nicht rückgängig gemacht werden.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 aktive Pflanze wird als entfernt archiviert.} other{{count} aktive Pflanzen werden als entfernt archiviert.}}",
  "spaceDetailDeleteSpace": "Bereich löschen",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" gelöscht · 1 Pflanze archiviert} other{\"{name}\" gelöscht · {count} Pflanzen archiviert}}",
  "spaceDetailDeleted": "\"{name}\" gelöscht",
  "spaceDetailViewPlantTimelineTooltip": "Pflanzen-Zeitachse ansehen",
  "spaceDetailNutrientCalculatorTooltip": "Nährstoffrechner",
  "spaceDetailLogCareAllTooltip": "Pflege für alle Pflanzen protokollieren",
  "spaceDetailCurrentConditions": "Aktuelle Bedingungen",
  "spaceDetailLastReading": "Letzte Messung: {date}",
  "spaceDetailNoReadingsYet": "Noch keine Messungen erfasst",
  "spaceDetailTemperature": "Temperatur",
  "spaceDetailHumidity": "Luftfeuchte",
  "spaceDetailViewFullAnalytics": "Vollständige Analyse ansehen",
  "spaceDetailAnalyticsSubtitle": "Phasenübersicht · VPD · Serien",
  "spaceDetailThresholdsSaved": "Grenzwerte gespeichert",
  "spaceDetailLightCalculator": "Lichtrechner",
  "spaceDetailLightCalcSubtitle": "Berechne das tägliche Lichtintegral aus PPFD und Photoperiode.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Photoperiode",
  "spaceDetailStage": "Phase",
  "spaceDetailHours": "Stunden",
  "spaceDetailStageSeedling": "Sämling",
  "spaceDetailStageVegetative": "Wachstum",
  "spaceDetailStageFlowering": "Blüte",
  "spaceDetailStageLateFlower": "Spätblüte",
  "spaceDetailDliTooLow": "Zu niedrig",
  "spaceDetailDliTooHigh": "Zu hoch",
  "spaceDetailSeedlingDli": "Sämling-DLI",
  "spaceDetailVegetativeDli": "Wachstums-DLI",
  "spaceDetailFloweringDli": "Blüte-DLI",
  "spaceDetailHistoryCount": "Verlauf ({count})",
  "spaceDetailNoReadingsEmpty": "Noch keine Messungen\nTippe auf Umgebung erfassen",
  "spaceDetailLogEntryDeleted": "Eintrag gelöscht",
  "spaceDetailLogEntryDeletedSubtitle": "Der Umgebungseintrag\nwurde entfernt.",
  "spaceDetailShowLess": "Weniger anzeigen",
  "spaceDetailShowAllReadings": "Alle {count} Messungen anzeigen",
  "spaceDetailCareScheduleSaved": "Pflegeplan gespeichert",
  "spaceDetailEveryNDays": "{count, plural, =1{Jeden Tag} other{Alle {count} Tage}}",
  "spaceDetailCareSchedule": "Pflegeplan",
  "spaceDetailSpaceWide": "Bereichsweit",
  "spaceDetailOneScheduleAll": "Ein Plan für alle Pflanzen in diesem Bereich.",
  "spaceDetailWatering": "Gießen",
  "spaceDetailFeeding": "Düngen",
  "spaceDetailIpmInspection": "IPM / Schädlingskontrolle",
  "spaceDetailSaveSchedule": "Plan speichern",
  "spaceDetailPlantsCount": "Pflanzen ({count})",
 },
 "fr": {
  "spaceDetailEditSpace": "Modifier l'espace",
  "spaceDetailEditSpaceSubtitle": "Modifier le nom, le type et l'équipement",
  "spaceDetailSpaceNameLabel": "Nom de l'espace *",
  "spaceDetailTypeLabel": "Type",
  "spaceDetailNotesOptionalLabel": "Notes (facultatif)",
  "spaceDetailHardwareOptional": "Équipement (facultatif)",
  "spaceDetailWattageLabel": "Puissance",
  "spaceDetailAreaLabel": "Surface",
  "spaceDetailSaveChanges": "Enregistrer",
  "spaceDetailSpaceUpdatedToast": "Espace mis à jour",
  "spaceDetailHumidityPctLabel": "Humidité (%)",
  "spaceDetailSaveReading": "Enregistrer le relevé",
  "spaceDetailEnterTempOrHumidity": "Saisis au moins une température ou une humidité",
  "spaceDetailOptimal": "Optimal",
  "spaceDetailCheck": "À vérifier",
  "spaceDetailNoData": "Aucune donnée",
  "spaceDetailIdealRange": "Idéal {range}",
  "spaceDetailDeleteSpaceTitle": "Supprimer « {name} » ?",
  "spaceDetailCannotBeUndone": "Cette action est irréversible.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 plante active sera archivée comme retirée.} other{{count} plantes actives seront archivées comme retirées.}}",
  "spaceDetailDeleteSpace": "Supprimer l'espace",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{« {name} » supprimé · 1 plante archivée} other{« {name} » supprimé · {count} plantes archivées}}",
  "spaceDetailDeleted": "« {name} » supprimé",
  "spaceDetailViewPlantTimelineTooltip": "Voir la chronologie des plantes",
  "spaceDetailNutrientCalculatorTooltip": "Calculateur de nutriments",
  "spaceDetailLogCareAllTooltip": "Consigner les soins pour toutes les plantes",
  "spaceDetailCurrentConditions": "Conditions actuelles",
  "spaceDetailLastReading": "Dernier relevé : {date}",
  "spaceDetailNoReadingsYet": "Aucun relevé enregistré",
  "spaceDetailTemperature": "Température",
  "spaceDetailHumidity": "Humidité",
  "spaceDetailViewFullAnalytics": "Voir l'analyse complète",
  "spaceDetailAnalyticsSubtitle": "phases · DPV · séries",
  "spaceDetailThresholdsSaved": "Seuils enregistrés",
  "spaceDetailLightCalculator": "Calculateur de lumière",
  "spaceDetailLightCalcSubtitle": "Calcule l'intégrale lumineuse quotidienne à partir du PPFD et de la photopériode.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Photopériode",
  "spaceDetailStage": "Phase",
  "spaceDetailHours": "Heures",
  "spaceDetailStageSeedling": "Semis",
  "spaceDetailStageVegetative": "Végétatif",
  "spaceDetailStageFlowering": "Floraison",
  "spaceDetailStageLateFlower": "Floraison tardive",
  "spaceDetailDliTooLow": "Trop faible",
  "spaceDetailDliTooHigh": "Trop élevé",
  "spaceDetailSeedlingDli": "DLI semis",
  "spaceDetailVegetativeDli": "DLI végétatif",
  "spaceDetailFloweringDli": "DLI floraison",
  "spaceDetailHistoryCount": "Historique ({count})",
  "spaceDetailNoReadingsEmpty": "Aucun relevé\nTouche Consigner l'environnement pour commencer",
  "spaceDetailLogEntryDeleted": "Relevé supprimé",
  "spaceDetailLogEntryDeletedSubtitle": "Le relevé d'environnement\na été supprimé.",
  "spaceDetailShowLess": "Voir moins",
  "spaceDetailShowAllReadings": "Voir les {count} relevés",
  "spaceDetailCareScheduleSaved": "Programme de soins enregistré",
  "spaceDetailEveryNDays": "{count, plural, =1{Chaque jour} other{Tous les {count} jours}}",
  "spaceDetailCareSchedule": "Programme de soins",
  "spaceDetailSpaceWide": "Tout l'espace",
  "spaceDetailOneScheduleAll": "Un programme pour toutes les plantes de cet espace.",
  "spaceDetailWatering": "Arrosage",
  "spaceDetailFeeding": "Fertilisation",
  "spaceDetailIpmInspection": "Lutte intégrée / Inspection",
  "spaceDetailSaveSchedule": "Enregistrer le programme",
  "spaceDetailPlantsCount": "Plantes ({count})",
 },
 "pt": {
  "spaceDetailEditSpace": "Editar espaço",
  "spaceDetailEditSpaceSubtitle": "Atualize nome, tipo e equipamento",
  "spaceDetailSpaceNameLabel": "Nome do espaço *",
  "spaceDetailTypeLabel": "Tipo",
  "spaceDetailNotesOptionalLabel": "Notas (opcional)",
  "spaceDetailHardwareOptional": "Equipamento (opcional)",
  "spaceDetailWattageLabel": "Potência",
  "spaceDetailAreaLabel": "Área",
  "spaceDetailSaveChanges": "Salvar alterações",
  "spaceDetailSpaceUpdatedToast": "Espaço atualizado",
  "spaceDetailHumidityPctLabel": "Umidade (%)",
  "spaceDetailSaveReading": "Salvar leitura",
  "spaceDetailEnterTempOrHumidity": "Informe pelo menos temperatura ou umidade",
  "spaceDetailOptimal": "Ótimo",
  "spaceDetailCheck": "Verificar",
  "spaceDetailNoData": "Sem dados",
  "spaceDetailIdealRange": "Ideal {range}",
  "spaceDetailDeleteSpaceTitle": "Excluir \"{name}\"?",
  "spaceDetailCannotBeUndone": "Esta ação não pode ser desfeita.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 planta ativa será arquivada como removida.} other{{count} plantas ativas serão arquivadas como removidas.}}",
  "spaceDetailDeleteSpace": "Excluir espaço",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" excluído · 1 planta arquivada} other{\"{name}\" excluído · {count} plantas arquivadas}}",
  "spaceDetailDeleted": "\"{name}\" excluído",
  "spaceDetailViewPlantTimelineTooltip": "Ver linha do tempo das plantas",
  "spaceDetailNutrientCalculatorTooltip": "Calculadora de nutrientes",
  "spaceDetailLogCareAllTooltip": "Registrar cuidados para todas as plantas",
  "spaceDetailCurrentConditions": "Condições atuais",
  "spaceDetailLastReading": "Última leitura: {date}",
  "spaceDetailNoReadingsYet": "Nenhuma leitura registrada",
  "spaceDetailTemperature": "Temperatura",
  "spaceDetailHumidity": "Umidade",
  "spaceDetailViewFullAnalytics": "Ver análise completa",
  "spaceDetailAnalyticsSubtitle": "fases · DPV · sequências",
  "spaceDetailThresholdsSaved": "Limites salvos",
  "spaceDetailLightCalculator": "Calculadora de luz",
  "spaceDetailLightCalcSubtitle": "Calcule a integral diária de luz a partir do PPFD e do fotoperíodo.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Fotoperíodo",
  "spaceDetailStage": "Fase",
  "spaceDetailHours": "Horas",
  "spaceDetailStageSeedling": "Muda",
  "spaceDetailStageVegetative": "Vegetativo",
  "spaceDetailStageFlowering": "Floração",
  "spaceDetailStageLateFlower": "Floração tardia",
  "spaceDetailDliTooLow": "Muito baixo",
  "spaceDetailDliTooHigh": "Muito alto",
  "spaceDetailSeedlingDli": "DLI muda",
  "spaceDetailVegetativeDli": "DLI vegetativo",
  "spaceDetailFloweringDli": "DLI floração",
  "spaceDetailHistoryCount": "Histórico ({count})",
  "spaceDetailNoReadingsEmpty": "Nenhuma leitura ainda\nToque em Registrar Ambiente para começar",
  "spaceDetailLogEntryDeleted": "Registro excluído",
  "spaceDetailLogEntryDeletedSubtitle": "O registro de ambiente\nfoi removido.",
  "spaceDetailShowLess": "Mostrar menos",
  "spaceDetailShowAllReadings": "Mostrar todas as {count} leituras",
  "spaceDetailCareScheduleSaved": "Cronograma de cuidados salvo",
  "spaceDetailEveryNDays": "{count, plural, =1{Todos os dias} other{A cada {count} dias}}",
  "spaceDetailCareSchedule": "Cronograma de cuidados",
  "spaceDetailSpaceWide": "Espaço inteiro",
  "spaceDetailOneScheduleAll": "Um cronograma para todas as plantas deste espaço.",
  "spaceDetailWatering": "Rega",
  "spaceDetailFeeding": "Fertilização",
  "spaceDetailIpmInspection": "MIP / Inspeção de pragas",
  "spaceDetailSaveSchedule": "Salvar cronograma",
  "spaceDetailPlantsCount": "Plantas ({count})",
 },
 "it": {
  "spaceDetailEditSpace": "Modifica spazio",
  "spaceDetailEditSpaceSubtitle": "Aggiorna nome, tipo e attrezzatura",
  "spaceDetailSpaceNameLabel": "Nome dello spazio *",
  "spaceDetailTypeLabel": "Tipo",
  "spaceDetailNotesOptionalLabel": "Note (facoltativo)",
  "spaceDetailHardwareOptional": "Attrezzatura (facoltativa)",
  "spaceDetailWattageLabel": "Potenza",
  "spaceDetailAreaLabel": "Superficie",
  "spaceDetailSaveChanges": "Salva modifiche",
  "spaceDetailSpaceUpdatedToast": "Spazio aggiornato",
  "spaceDetailHumidityPctLabel": "Umidità (%)",
  "spaceDetailSaveReading": "Salva lettura",
  "spaceDetailEnterTempOrHumidity": "Inserisci almeno temperatura o umidità",
  "spaceDetailOptimal": "Ottimale",
  "spaceDetailCheck": "Da controllare",
  "spaceDetailNoData": "Nessun dato",
  "spaceDetailIdealRange": "Ideale {range}",
  "spaceDetailDeleteSpaceTitle": "Eliminare \"{name}\"?",
  "spaceDetailCannotBeUndone": "Questa azione non può essere annullata.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 pianta attiva verrà archiviata come rimossa.} other{{count} piante attive verranno archiviate come rimosse.}}",
  "spaceDetailDeleteSpace": "Elimina spazio",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" eliminato · 1 pianta archiviata} other{\"{name}\" eliminato · {count} piante archiviate}}",
  "spaceDetailDeleted": "\"{name}\" eliminato",
  "spaceDetailViewPlantTimelineTooltip": "Vedi cronologia piante",
  "spaceDetailNutrientCalculatorTooltip": "Calcolatore nutrienti",
  "spaceDetailLogCareAllTooltip": "Registra cure per tutte le piante",
  "spaceDetailCurrentConditions": "Condizioni attuali",
  "spaceDetailLastReading": "Ultima lettura: {date}",
  "spaceDetailNoReadingsYet": "Nessuna lettura registrata",
  "spaceDetailTemperature": "Temperatura",
  "spaceDetailHumidity": "Umidità",
  "spaceDetailViewFullAnalytics": "Vedi analisi completa",
  "spaceDetailAnalyticsSubtitle": "fasi · VPD · serie",
  "spaceDetailThresholdsSaved": "Soglie salvate",
  "spaceDetailLightCalculator": "Calcolatore di luce",
  "spaceDetailLightCalcSubtitle": "Calcola l'integrale di luce giornaliero da PPFD e fotoperiodo.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Fotoperiodo",
  "spaceDetailStage": "Fase",
  "spaceDetailHours": "Ore",
  "spaceDetailStageSeedling": "Piantina",
  "spaceDetailStageVegetative": "Vegetativa",
  "spaceDetailStageFlowering": "Fioritura",
  "spaceDetailStageLateFlower": "Fioritura tardiva",
  "spaceDetailDliTooLow": "Troppo basso",
  "spaceDetailDliTooHigh": "Troppo alto",
  "spaceDetailSeedlingDli": "DLI piantina",
  "spaceDetailVegetativeDli": "DLI vegetativa",
  "spaceDetailFloweringDli": "DLI fioritura",
  "spaceDetailHistoryCount": "Cronologia ({count})",
  "spaceDetailNoReadingsEmpty": "Nessuna lettura\nTocca Registra ambiente per iniziare",
  "spaceDetailLogEntryDeleted": "Voce eliminata",
  "spaceDetailLogEntryDeletedSubtitle": "La voce di ambiente\nè stata rimossa.",
  "spaceDetailShowLess": "Mostra meno",
  "spaceDetailShowAllReadings": "Mostra tutte le {count} letture",
  "spaceDetailCareScheduleSaved": "Programma di cura salvato",
  "spaceDetailEveryNDays": "{count, plural, =1{Ogni giorno} other{Ogni {count} giorni}}",
  "spaceDetailCareSchedule": "Programma di cura",
  "spaceDetailSpaceWide": "Tutto lo spazio",
  "spaceDetailOneScheduleAll": "Un programma per tutte le piante di questo spazio.",
  "spaceDetailWatering": "Irrigazione",
  "spaceDetailFeeding": "Concimazione",
  "spaceDetailIpmInspection": "IPM / Ispezione parassiti",
  "spaceDetailSaveSchedule": "Salva programma",
  "spaceDetailPlantsCount": "Piante ({count})",
 },
 "nl": {
  "spaceDetailEditSpace": "Ruimte bewerken",
  "spaceDetailEditSpaceSubtitle": "Naam, type en apparatuur bijwerken",
  "spaceDetailSpaceNameLabel": "Naam van ruimte *",
  "spaceDetailTypeLabel": "Type",
  "spaceDetailNotesOptionalLabel": "Notities (optioneel)",
  "spaceDetailHardwareOptional": "Apparatuur (optioneel)",
  "spaceDetailWattageLabel": "Vermogen",
  "spaceDetailAreaLabel": "Oppervlakte",
  "spaceDetailSaveChanges": "Wijzigingen opslaan",
  "spaceDetailSpaceUpdatedToast": "Ruimte bijgewerkt",
  "spaceDetailHumidityPctLabel": "Vochtigheid (%)",
  "spaceDetailSaveReading": "Meting opslaan",
  "spaceDetailEnterTempOrHumidity": "Voer minstens een temperatuur of vochtigheid in",
  "spaceDetailOptimal": "Optimaal",
  "spaceDetailCheck": "Controleren",
  "spaceDetailNoData": "Geen gegevens",
  "spaceDetailIdealRange": "Ideaal {range}",
  "spaceDetailDeleteSpaceTitle": "\"{name}\" verwijderen?",
  "spaceDetailCannotBeUndone": "Deze actie kan niet ongedaan worden gemaakt.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 actieve plant wordt gearchiveerd als verwijderd.} other{{count} actieve planten worden gearchiveerd als verwijderd.}}",
  "spaceDetailDeleteSpace": "Ruimte verwijderen",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" verwijderd · 1 plant gearchiveerd} other{\"{name}\" verwijderd · {count} planten gearchiveerd}}",
  "spaceDetailDeleted": "\"{name}\" verwijderd",
  "spaceDetailViewPlantTimelineTooltip": "Planttijdlijn bekijken",
  "spaceDetailNutrientCalculatorTooltip": "Voedingscalculator",
  "spaceDetailLogCareAllTooltip": "Verzorging voor alle planten loggen",
  "spaceDetailCurrentConditions": "Huidige omstandigheden",
  "spaceDetailLastReading": "Laatste meting: {date}",
  "spaceDetailNoReadingsYet": "Nog geen metingen gelogd",
  "spaceDetailTemperature": "Temperatuur",
  "spaceDetailHumidity": "Vochtigheid",
  "spaceDetailViewFullAnalytics": "Volledige analyse bekijken",
  "spaceDetailAnalyticsSubtitle": "fase-overzicht · VPD · reeksen",
  "spaceDetailThresholdsSaved": "Drempels opgeslagen",
  "spaceDetailLightCalculator": "Lichtcalculator",
  "spaceDetailLightCalcSubtitle": "Bereken de dagelijkse lichtintegraal uit PPFD en fotoperiode.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Fotoperiode",
  "spaceDetailStage": "Fase",
  "spaceDetailHours": "Uren",
  "spaceDetailStageSeedling": "Zaailing",
  "spaceDetailStageVegetative": "Vegetatief",
  "spaceDetailStageFlowering": "Bloei",
  "spaceDetailStageLateFlower": "Late bloei",
  "spaceDetailDliTooLow": "Te laag",
  "spaceDetailDliTooHigh": "Te hoog",
  "spaceDetailSeedlingDli": "Zaailing-DLI",
  "spaceDetailVegetativeDli": "Vegetatieve DLI",
  "spaceDetailFloweringDli": "Bloei-DLI",
  "spaceDetailHistoryCount": "Geschiedenis ({count})",
  "spaceDetailNoReadingsEmpty": "Nog geen metingen\nTik op Omgeving loggen om te beginnen",
  "spaceDetailLogEntryDeleted": "Logboekitem verwijderd",
  "spaceDetailLogEntryDeletedSubtitle": "Het omgevingslogboekitem\nis verwijderd.",
  "spaceDetailShowLess": "Minder tonen",
  "spaceDetailShowAllReadings": "Alle {count} metingen tonen",
  "spaceDetailCareScheduleSaved": "Verzorgingsschema opgeslagen",
  "spaceDetailEveryNDays": "{count, plural, =1{Elke dag} other{Elke {count} dagen}}",
  "spaceDetailCareSchedule": "Verzorgingsschema",
  "spaceDetailSpaceWide": "Hele ruimte",
  "spaceDetailOneScheduleAll": "Eén schema voor alle planten in deze ruimte.",
  "spaceDetailWatering": "Water geven",
  "spaceDetailFeeding": "Voeden",
  "spaceDetailIpmInspection": "IPM / Plaaginspectie",
  "spaceDetailSaveSchedule": "Schema opslaan",
  "spaceDetailPlantsCount": "Planten ({count})",
 },
 "af": {
  "spaceDetailEditSpace": "Wysig spasie",
  "spaceDetailEditSpaceSubtitle": "Werk naam, tipe en toerusting by",
  "spaceDetailSpaceNameLabel": "Spasienaam *",
  "spaceDetailTypeLabel": "Tipe",
  "spaceDetailNotesOptionalLabel": "Notas (opsioneel)",
  "spaceDetailHardwareOptional": "Toerusting (opsioneel)",
  "spaceDetailWattageLabel": "Wattasie",
  "spaceDetailAreaLabel": "Oppervlakte",
  "spaceDetailSaveChanges": "Stoor veranderinge",
  "spaceDetailSpaceUpdatedToast": "Spasie bygewerk",
  "spaceDetailHumidityPctLabel": "Humiditeit (%)",
  "spaceDetailSaveReading": "Stoor lesing",
  "spaceDetailEnterTempOrHumidity": "Voer ten minste 'n temperatuur of humiditeit in",
  "spaceDetailOptimal": "Optimaal",
  "spaceDetailCheck": "Kontroleer",
  "spaceDetailNoData": "Geen data nie",
  "spaceDetailIdealRange": "Ideaal {range}",
  "spaceDetailDeleteSpaceTitle": "Skrap \"{name}\"?",
  "spaceDetailCannotBeUndone": "Hierdie aksie kan nie ongedaan gemaak word nie.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{1 aktiewe plant sal as verwyder geargiveer word.} other{{count} aktiewe plante sal as verwyder geargiveer word.}}",
  "spaceDetailDeleteSpace": "Skrap spasie",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{\"{name}\" geskrap · 1 plant geargiveer} other{\"{name}\" geskrap · {count} plante geargiveer}}",
  "spaceDetailDeleted": "\"{name}\" geskrap",
  "spaceDetailViewPlantTimelineTooltip": "Bekyk plant-tydlyn",
  "spaceDetailNutrientCalculatorTooltip": "Voedingstofberekening",
  "spaceDetailLogCareAllTooltip": "Teken versorging vir alle plante aan",
  "spaceDetailCurrentConditions": "Huidige toestande",
  "spaceDetailLastReading": "Laaste lesing: {date}",
  "spaceDetailNoReadingsYet": "Nog geen lesings aangeteken nie",
  "spaceDetailTemperature": "Temperatuur",
  "spaceDetailHumidity": "Humiditeit",
  "spaceDetailViewFullAnalytics": "Bekyk volledige ontleding",
  "spaceDetailAnalyticsSubtitle": "fase-uiteensetting · VPD · reekse",
  "spaceDetailThresholdsSaved": "Drempels gestoor",
  "spaceDetailLightCalculator": "Ligberekening",
  "spaceDetailLightCalcSubtitle": "Bereken die daaglikse ligintegraal uit PPFD en fotoperiode.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Fotoperiode",
  "spaceDetailStage": "Fase",
  "spaceDetailHours": "Ure",
  "spaceDetailStageSeedling": "Saailing",
  "spaceDetailStageVegetative": "Vegetatief",
  "spaceDetailStageFlowering": "Blom",
  "spaceDetailStageLateFlower": "Laat blom",
  "spaceDetailDliTooLow": "Te laag",
  "spaceDetailDliTooHigh": "Te hoog",
  "spaceDetailSeedlingDli": "Saailing-DLI",
  "spaceDetailVegetativeDli": "Vegetatiewe DLI",
  "spaceDetailFloweringDli": "Blom-DLI",
  "spaceDetailHistoryCount": "Geskiedenis ({count})",
  "spaceDetailNoReadingsEmpty": "Nog geen lesings nie\nTik Teken omgewing aan om te begin",
  "spaceDetailLogEntryDeleted": "Inskrywing geskrap",
  "spaceDetailLogEntryDeletedSubtitle": "Die omgewingsinskrywing\nis verwyder.",
  "spaceDetailShowLess": "Wys minder",
  "spaceDetailShowAllReadings": "Wys al {count} lesings",
  "spaceDetailCareScheduleSaved": "Versorgingskedule gestoor",
  "spaceDetailEveryNDays": "{count, plural, =1{Elke dag} other{Elke {count} dae}}",
  "spaceDetailCareSchedule": "Versorgingskedule",
  "spaceDetailSpaceWide": "Hele spasie",
  "spaceDetailOneScheduleAll": "Een skedule vir alle plante in hierdie spasie.",
  "spaceDetailWatering": "Natmaak",
  "spaceDetailFeeding": "Voeding",
  "spaceDetailIpmInspection": "IPM / Plaaginspeksie",
  "spaceDetailSaveSchedule": "Stoor skedule",
  "spaceDetailPlantsCount": "Plante ({count})",
 },
 "zu": {
  "spaceDetailEditSpace": "Hlela indawo",
  "spaceDetailEditSpaceSubtitle": "Buyekeza igama, uhlobo nezinsiza",
  "spaceDetailSpaceNameLabel": "Igama lendawo *",
  "spaceDetailTypeLabel": "Uhlobo",
  "spaceDetailNotesOptionalLabel": "Amanothi (okuzikhethela)",
  "spaceDetailHardwareOptional": "Izinsiza (okuzikhethela)",
  "spaceDetailWattageLabel": "Amandla",
  "spaceDetailAreaLabel": "Indawo",
  "spaceDetailSaveChanges": "Londoloza izinguquko",
  "spaceDetailSpaceUpdatedToast": "Indawo ibuyekeziwe",
  "spaceDetailHumidityPctLabel": "Umswakama (%)",
  "spaceDetailSaveReading": "Londoloza ukufunda",
  "spaceDetailEnterTempOrHumidity": "Faka okungenani izinga lokushisa noma umswakama",
  "spaceDetailOptimal": "Kuhle",
  "spaceDetailCheck": "Hlola",
  "spaceDetailNoData": "Ayikho idatha",
  "spaceDetailIdealRange": "Okuhle: {range}",
  "spaceDetailDeleteSpaceTitle": "Susa i-\"{name}\"?",
  "spaceDetailCannotBeUndone": "Lesi senzo asikwazi ukuhlehliswa.",
  "spaceDetailPlantsWillBeArchived": "{count, plural, =1{Isitshalo esi-1 esisebenzayo sizogcinwa njengesisusiwe.} other{Izitshalo ezingu-{count} ezisebenzayo zizogcinwa njengezisusiwe.}}",
  "spaceDetailDeleteSpace": "Susa indawo",
  "spaceDetailDeletedWithArchived": "{count, plural, =1{I-\"{name}\" isusiwe · isitshalo esi-1 sigciniwe} other{I-\"{name}\" isusiwe · izitshalo ezingu-{count} zigciniwe}}",
  "spaceDetailDeleted": "I-\"{name}\" isusiwe",
  "spaceDetailViewPlantTimelineTooltip": "Buka uhlu lwezehlakalo zezitshalo",
  "spaceDetailNutrientCalculatorTooltip": "Isibali sezakhamzimba",
  "spaceDetailLogCareAllTooltip": "Rekhoda ukunakekelwa kwazo zonke izitshalo",
  "spaceDetailCurrentConditions": "Izimo zamanje",
  "spaceDetailLastReading": "Ukufunda kokugcina: {date}",
  "spaceDetailNoReadingsYet": "Akukho ukufunda okurekhodiwe okwamanje",
  "spaceDetailTemperature": "Izinga lokushisa",
  "spaceDetailHumidity": "Umswakama",
  "spaceDetailViewFullAnalytics": "Buka ukuhlaziya okuphelele",
  "spaceDetailAnalyticsSubtitle": "izigaba · i-VPD · ukulandelana",
  "spaceDetailThresholdsSaved": "Imikhawulo ilondoloziwe",
  "spaceDetailLightCalculator": "Isibali sokukhanya",
  "spaceDetailLightCalcSubtitle": "Bala inani lokukhanya kwansuku zonke kusuka ku-PPFD nenkathi yokukhanya.",
  "spaceDetailPpfd": "PPFD",
  "spaceDetailPhotoperiod": "Inkathi yokukhanya",
  "spaceDetailStage": "Isigaba",
  "spaceDetailHours": "Amahora",
  "spaceDetailStageSeedling": "Isithombo",
  "spaceDetailStageVegetative": "Ukukhula",
  "spaceDetailStageFlowering": "Ukuqhakaza",
  "spaceDetailStageLateFlower": "Ukuqhakaza sekwephuzile",
  "spaceDetailDliTooLow": "Kuphansi kakhulu",
  "spaceDetailDliTooHigh": "Kuphezulu kakhulu",
  "spaceDetailSeedlingDli": "I-DLI yesithombo",
  "spaceDetailVegetativeDli": "I-DLI yokukhula",
  "spaceDetailFloweringDli": "I-DLI yokuqhakaza",
  "spaceDetailHistoryCount": "Umlando ({count})",
  "spaceDetailNoReadingsEmpty": "Akukho ukufunda okwamanje\nThepha u-Rekhoda imvelo ukuqala",
  "spaceDetailLogEntryDeleted": "Irekhodi lisusiwe",
  "spaceDetailLogEntryDeletedSubtitle": "Irekhodi lemvelo\nlisusiwe.",
  "spaceDetailShowLess": "Bonisa okuncane",
  "spaceDetailShowAllReadings": "Bonisa konke ukufunda okungu-{count}",
  "spaceDetailCareScheduleSaved": "Ishedyuli yokunakekela ilondoloziwe",
  "spaceDetailEveryNDays": "{count, plural, =1{Nsuku zonke} other{Njalo ezinsukwini ezingu-{count}}}",
  "spaceDetailCareSchedule": "Ishedyuli yokunakekela",
  "spaceDetailSpaceWide": "Indawo yonke",
  "spaceDetailOneScheduleAll": "Ishedyuli eyodwa yazo zonke izitshalo kule ndawo.",
  "spaceDetailWatering": "Ukunisela",
  "spaceDetailFeeding": "Ukondla",
  "spaceDetailIpmInspection": "I-IPM / Ukuhlola izinambuzane",
  "spaceDetailSaveSchedule": "Londoloza ishedyuli",
  "spaceDetailPlantsCount": "Izitshalo ({count})",
 },
}


def main() -> None:
    base = os.path.join("lib", "l10n")
    for locale, entries in L.items():
        path = os.path.join(base, f"app_{locale}.arb")
        with io.open(path, encoding="utf-8") as f:
            data = json.load(f)
        if "spaceDetailEditSpace" in data:
            print(f"skip {path} (already migrated)")
            continue
        with io.open(path, encoding="utf-8") as f:
            text = f.read().rstrip()
        assert text.endswith("}")
        body = ",\n".join(
            f'  "{k}": {json.dumps(v, ensure_ascii=False)}'
            for k, v in entries.items()
        )
        text = text[: text.rfind("}")].rstrip().rstrip(",")
        text += ",\n\n" + body + "\n}\n"
        json.loads(text)  # validate before writing
        with io.open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote {len(entries)} keys -> {path}")


if __name__ == "__main__":
    main()
